### ISSUE TITLE
Offer offline documentation

### ISSUE THREAD

**Issue by ChucksConsulting** [Sneeds-Feed-and-Seed/sneedacity#102]
Could be pdf

**Comment by woodenphone** [comment]
I'd appreciate more versatile and less bloated formats than PDF such manpages, markdown, texinfo and so on; with PDF being a derived format from simpler ones.
Ideally there should be minimum overhead required in terms of both dependencies and system requirements. e.g. A user on the command line should have no issue reading all documentation. 
Something such as this might help with deriving multiple formats from a single master set of documents: https://pandoc.org

**Comment by Furitenman** [comment]
Audacity already does that, they just download the .html files and open them as pages in the browser. We could do the same thing. A PDF alternative could also be added.

**Comment by meguminloli** [comment]
Maybe the best way to do this would be markdown files, converted to latex via pandoc and then pdf, html etc.

**Comment by Furitenman** [comment]
> 
> 
> Maybe the best way to do this would be markdown files, converted to latex via pandoc and then pdf, html etc.
>
I think they already do that, we would just need to copy it: https://www.audacityteam.org/help/documentation/
I assume none of you guys mean to write a new documentation from scratch. If we could get this slapped and working on Github, we don't even need hosting for it.

**Comment by georgebushfourtwenty** [comment]
I won't accept this unless there's a pepe on each page.

**Comment by TheRealPSV** [comment]
On a related note, is it a good idea for the help links to still be pointing to the audacity site?

https://github.com/Sneeds-Feed-and-Seed/sneedacity/blob/0c9b779c8f556c2f06ad3e84c71b9eff3d5d8b64/help/sneedacity.appdata.xml#L28-L30

**Comment by woodenphone** [comment]
> On a related note, is it a good idea for the help links to still be pointing to the audacity site?
> 
> https://github.com/Sneeds-Feed-and-Seed/sneedacity/blob/0c9b779c8f556c2f06ad3e84c71b9eff3d5d8b64/help/sneedacity.appdata.xml#L28-L30

IMO Yes.
Until this fork has an alternative set of documentation (e.g. markdown files in the repo, website mirror) as a user I'd prefer to be pointed to any documentation over not finding the information on how to do things.

**Comment by ChucksConsulting** [comment]
There isn't enough manpower at the moment to do this.
