### ISSUE TITLE
4chan browser easter egg in sneedacity

### ISSUE THREAD

**Issue by denimchewer56** [Sneeds-Feed-and-Seed/sneedacity#103]
steps to trigger easter egg:
1. click on a track
2. enable caps lock
3. type "SNEED"

result: /g/ opens in the default browser

**Comment by moxniso** [comment]
based i'll see if i can do it

**Comment by moxniso** [comment]
fucking did it, opening a PR right now

**Comment by ChucksConsulting** [comment]
Done
