### ISSUE TITLE
among us easter egg

### ISSUE THREAD

**Issue by quisys** [Sneeds-Feed-and-Seed/sneedacity#104]
maybe add an option to play a version of among us written in emacs when you press a buttton???? idk

**Comment by diracs-delta** [comment]
@quisys dork

**Comment by jobbautista9** [comment]
sus

Though I think that should be a plugin instead, if that's possible

**Comment by sonsofsneed3** [comment]
sneed

**Comment by arceuss** [comment]
sussy

**Comment by meguminloli** [comment]
Rewriting amogus for Sneedacity sounds like overkill. Maybe Tetris would be better.

**Comment by quisys** [comment]
Too bad Tetris isn't funny

**Comment by Whatever-Green** [comment]
Really any Easter eggs will be a welcome addon

**Comment by binex-dsk** [comment]
Holy real

**Comment by ChucksConsulting** [comment]
If you can write some minimalist easter egg then submit it as a PR. But it needs to be something that is non-intrusive, not likely to cause issues and doesn't need maintenance.
