### ISSUE TITLE
Suggestion for new text logo

### ISSUE THREAD

**Issue by weevilgit** [Sneeds-Feed-and-Seed/sneedacity#114]
**Describe the solution you'd like**
Pic related would be more aligned with the simpsons theme without infringing on any copyrights. The font is based, but not stolen from the Simpsons logo. The color is the same as Sneed's.

![Sneedacity Logo Transparent](https://user-images.githubusercontent.com/69782583/124865446-1164c200-df91-11eb-9cd6-51b370938798.png)

Reference:
![Sneedacity Logo](https://user-images.githubusercontent.com/69782583/124865442-0f026800-df91-11eb-8f09-bafaed76a008.png)

Also, I commented some logo suggestions [here](https://github.com/Sneeds-Feed-and-Seed/sneedacity/pull/94#issuecomment-876050390) and I'm not sure if that's the right thing to do. Should I open a new issue with the images or did I submit them in the right place?

**Comment by sonsofsneed3** [comment]
I suggest not using the simpsons font and instead using the font for the sign on sneeds feed and seed

**Comment by Ckath** [comment]
looks nice, can be considered as well probably, there was also some talk about possibly using the old style audacity text again for the name.

> Also, I commented some logo suggestions [here](https://github.com/Sneeds-Feed-and-Seed/sneedacity/pull/94#issuecomment-876050390) and I'm not sure if that's the right thing to do. Should I open a new issue with the images or did I submit them in the right place?

need to group the whole logo discussion in one place anyway and have a vote/suggestion going thats more organized than the pr conversation thread, but yes thats where most of it is discussed atm. 
could maybe use a discussion with all options reformatted to be easy to vote on(?) in the nearby future.

also figure out the actual copyright and licensing info of what can and cant be gotten away with.

**Comment by sowa705** [comment]
I'd add a line to 'd' in sneedacity, current version looks too much line an 'o'
