### ISSUE TITLE
Readme misleading

### ISSUE THREAD

**Issue by to7m** [Sneeds-Feed-and-Seed/sneedacity#123]
In README.md: “Sneedacity (formerly Audacity)”

This implies that Audacity became Sneedacity, which isn't what happened. It's like saying LibreOffice (formerly OpenOffice).

I suggest “Sneedacity (fork of Audacity)”, where “fork of” is a link to a page explaining the situation.

**Comment by Eneocho** [comment]
It's a joke based on the Sneed meme. It's a sign that says "Sneed's Seed and Feed, Formerly Chuck's". The joke being that since Sneed, Seed and Feed rhyme, at one point it was called "Chuck's Suck and Fuck". So, while "misleading", the comedic value is worth it.

**Comment by to7m** [comment]
> It's a joke based on the Sneed meme.

That's irrelevant, the name's fine.

**Comment by Eneocho** [comment]
> 
> 
> > It's a joke based on the Sneed meme.
> 
> That's irrelevant, the name's fine.

I meant that the (formerly audacity) is the joke, not the sneedacity part.

**Comment by to7m** [comment]
> I meant that (formerly audacity) is the joke, not the sneedacity part.

Oh okay. Well, most people won't get the reference, so it's not just "misleading", it's misleading (without quotes).

**Comment by Genghius** [comment]
> > I meant that (formerly audacity) is the joke, not the sneedacity part.
> 
> Oh okay. Well, most people won't get the reference, so it's not just "misleading", it's misleading (without quotes).

so be it then, nothing wrong with being misleading.

**Comment by PlavorSeol** [comment]
Sneed's store was formerly Chuck's, Sneedacity wasn't formerly Audacity.

**Comment by Genghius** [comment]
> Sneed's store was formerly Chuck's, Sneedacity wasn't formerly Audacity.

Audacity without spyware was formerly audacity's. now it is Sneedacity's.

**Comment by Ckath** [comment]
`Sneedacity (formerly Audacity), an Audacity fork` is the best its going to be.

the joke is crucial to the sneed experience

**Comment by Genghius** [comment]
what about:
`Sneedacity (never was audacity), 100% original sequence of 0's and 1's. Any similarity to other sequences of 0's and 1's is pure coincidence`
?

**Comment by PlavorSeol** [comment]
Why don't we write `Sneedacity (formerly Chuckacity), an Audacity fork` and pretend as if we renamed it once after forking?

**Comment by to7m** [comment]
> `Sneedacity (formerly Audacity), an Audacity fork

This exact wording would still be an issue because most users aren't going to know what a fork is, but I guess something similar that explicitly contradicts “formerly Audacity” would solve the issue.

**Comment by Genghius** [comment]
>most users aren't going to know what a fork is

You are a troll and a bad one at that, btfo.

**Comment by Ckath** [comment]
your issue was, and I quote:
> This exact wording would still be an issue because most users aren't going to know what a fork is, but I guess something similar that explicitly contradicts “formerly Audacity” would solve the issue.

stating its a fork **solves** your issue, users grasp on technical jargon is not part of the issue or the projects problem

**Comment by N-R-K** [comment]
> This implies that Audacity became Sneedacity, which isn't what happened.

That's exactly what a fork is.

>  It's like saying LibreOffice (formerly OpenOffice).
from https://www.libreoffice.org
"LibreOffice is a free and powerful office suite, and a successor to OpenOffice"

**Comment by Ckath** [comment]
case closed, but thanks for the concern.
