### ISSUE TITLE
Autism representation

### ISSUE THREAD

**Issue by Masken8** [Sneeds-Feed-and-Seed/sneedacity#124]
**Is your feature request related to a problem? Please describe.**
Right now the README does not explicitly encourage autistic people to contribute. Neurodiversity is a key ingredient for better decision-making among teams. Homogenous groups may be susceptible to groupthink, while neurodiverse teams can leverage a greater variety of perspectives and are likely to consider information more thoroughly and accurately.

**Describe the solution you'd like**
I propose adding the SVG linked below to the README.
https://upload.wikimedia.org/wikipedia/commons/9/91/Neurodiversity_Symbol.svg

**Comment by ChucksConsulting** [comment]
Stop adding stupid shit

**Comment by Masken8** [comment]
No.

**Comment by eylles** [comment]
> **Is your feature request related to a problem? Please describe.**
> Right now the README does not explicitly encourage autistic people to contribute. Neurodiversity is a key ingredient for better decision-making among teams. Homogenous groups may be susceptible to groupthink, while neurodiverse teams can leverage a greater variety of perspectives and are likely to consider information more thoroughly and accurately.
> 
> **Describe the solution you'd like**
> I propose adding the SVG linked below to the README.
> https://upload.wikimedia.org/wikipedia/commons/9/91/Neurodiversity_Symbol.svg

There's already a 4chan link on the readme, if dat ain enuf nofing iz

**Comment by meguminloli** [comment]
@eylles is right. We already have a 4chan link in README, that's enough autism for this project.
