### ISSUE TITLE
Sneedacity Logo

### ISSUE THREAD

**Issue by NO-ob** [Sneeds-Feed-and-Seed/sneedacity#127]
![sneedacity](https://user-images.githubusercontent.com/15161159/124959453-1c603680-e013-11eb-8be0-6646f8248964.png)
[sneedacity.psd.zip](https://github.com/Sneeds-Feed-and-Seed/sneedacity/files/6786020/sneedacity.psd.zip)

Font for text https://www.dafont.com/simpsonfont.font

**Comment by Ckath** [comment]
already a lot of options discussed in #94 , might want to add it there till a new place is discussed

**Comment by Genghius** [comment]
I got this logo proposal, why have the app name in the logo when you can have its origin uwu.
![image](https://user-images.githubusercontent.com/62076069/124986618-b9cb6280-e033-11eb-8439-8120aab0b71e.png)
