### ISSUE TITLE
Delete the extra branches

### ISSUE THREAD

**Issue by ChucksConsulting** [Sneeds-Feed-and-Seed/sneedacity#131]
All of the other branches are old and irrelevant except 'wxwidgets' and maybe 'release-3.0.3', but I don't see a reason not to get rid of that one as we haven't changed anything there - it's just default Audacity.

**Comment by meguminloli** [comment]
Aren't you a jannie too?

**Comment by ChucksConsulting** [comment]
Nah

**Comment by Ckath** [comment]
its been pending for like a day at least
![image](https://user-images.githubusercontent.com/15038414/124993714-4118d600-e034-11eb-978e-ce275972e0fa.png)

**Comment by ChucksConsulting** [comment]
> its been pending for like a day at least
> ![image](https://user-images.githubusercontent.com/15038414/124993714-4118d600-e034-11eb-978e-ce275972e0fa.png)

I don't see anything in my notifications

**Comment by ChucksConsulting** [comment]
Done, should be easy to get them back with https://stackoverflow.com/questions/9537392/git-fetch-remote-branch
