### ISSUE TITLE
Use git submodules for the dependencies

### ISSUE THREAD

**Issue by ChucksConsulting** [Sneeds-Feed-and-Seed/sneedacity#137]
That way it would be easier to update them.

**Comment by meguminloli** [comment]
It's not really a good thing. We should try if they didn't change API. Also the `git clone` would take longer. Maybe, integrate the `git clone` into CMake? And only clone if the host system doesn't have that dependency?

**Comment by ChucksConsulting** [comment]
It would help us make sure the program works correctly with the upstream version of any given library. Of course I mean doing it after making sure that it actually works with a given version.

**Comment by 0kalekale** [comment]
might as well port the build system to meson at this point

**Comment by ChucksConsulting** [comment]
Maybe in the future.
