### ISSUE TITLE
Decide a version scheme

### ISSUE THREAD

**Issue by ChucksConsulting** [Sneeds-Feed-and-Seed/sneedacity#138]
How are we going to number our releases? Are we going to track the upstream version?

**Comment by ChucksConsulting** [comment]
>I say track upstream + Sneedacity enhancements version. So to say, when a Sneedacity-exclusive feature gets added, Sneedacity enhancements version gets bumped. For example 3.0.$CURR_VER+d; when some major or several minor enhancement get merged it'll bump to 3.0.$CURR_VER+e

**Comment by Ckath** [comment]
also thought about it related to #145 , as long as it makes upstream version clear it should be fine. but special signs in versions get annoying with packaging so its best to keep it as simple as possible.

the upstream releases are always `x.y.z` so the most straight forward solution I see would be to just add some sneedacity versions to the end like `x.y.z.s`. meaning if we were to do a `3.0.3` based release soon it'd just be `3.0.3.0` then another one `3.0.3.1` etc, can go double digits if we need it. and then just reset to `.0` when upstream goes `3.0.4`

**Comment by Ckath** [comment]
that does leave out the whole deal with RCs like when it was `3.0.3-RC1` and later went to `3.0.3-RC2` but I think we can just safely ignore the whole RC cycle for releases with the scale of this project.

like how if we were to do something now with releases it'd be fine as `3.0.2.0` even though upstream has `3.0.3-RC2`. if the RCs do some important commit we'd want to also get in our release we can always throw out a `3.0.3.0-RC`
