### ISSUE TITLE
SNEED Clarification

### ISSUE THREAD

**Issue by sonsofsneed3** [Sneeds-Feed-and-Seed/sneedacity#139]
Sneed is not a simpsons meme

Sneed is NOT the simpsons

In fact Sneeders are anti-Simpsons

Please keep sneedacity related and refrain from any disgusting simpsons references at all costs

Thank you

**Comment by binex-dsk** [comment]
![image](https://user-images.githubusercontent.com/65276418/125005239-4cb2cf80-e029-11eb-95aa-7c240c959d50.png)

**Comment by Ckath** [comment]
it is merely a joke sir
