### ISSUE TITLE
Add support for creating and exporting .wav files with loop points

### ISSUE THREAD

**Issue by WhatsitTooya24** [Sneeds-Feed-and-Seed/sneedacity#143]
It would be cool if we could get support for .wav loop points. Currently if you want to add loop points, you'll have to use another piece of software. I've been using Wavosaur, their loop point feature is documented [here.](https://www.wavosaur.com/quick-help/loop-points-edition.php) It would be nice to not have to swap between programs. The option could probably be added to either the Edit or Tracks dropdown. I think [this PDF](http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/Docs/RIFFNEW.pdf) contains documentation for wave loop points.

Lets get Sneedacity to become the definitive audio editing FOSS, keep up the good work sneedbros.

**Comment by L1pE** [comment]
Also known as "cue points". Libsndfile can display cue points via sndfile-info, and ffmpeg via ffprobe which it displays as a chapter, neither can add or edit cue points AFAIK though. 

I've looked far and wide and there is no libre software that supports editing .wav cue points, even though there's requests for it in a few apps including Audacity that go back over 10 years. Sneedacity would be the first if it got implemented.

**Comment by ChucksConsulting** [comment]
How would you implement this? If you can make a diagram of how you would lay out the menus and such it would be a big help.

**Comment by ornxka** [comment]
Is anyone else interested in implementing this? If not, I'll volunteer.

**Comment by L1pE** [comment]
> How would you implement this? If you can make a diagram of how you would lay out the menus and such it would be a big help.

Honestly, you could just hijack the entire Labels UI for this, but I am unsure how to go about it without either making it too hidden or too redundant.

Also, stumbled upon this, maybe helpful: https://bleepsandpops.com/post/37792760450/adding-cue-points-to-wav-files-in-c

**Comment by WhatsitTooya24** [comment]
> How would you implement this? If you can make a diagram of how you would lay out the menus and such it would be a big help.

If we're going for a basic implementation of loop points (just supporting loop cues, ignoring ping-pong loop cues) we could pretty much take a page out of Wavosaur's book. The way they have it is you simply select a range and it creates loop points at the beginning and end of the range. This would also work well with how a loop is made, considering the best way is to highlight the range you want, then select at zero crossings.

[Pic related](https://i.imgur.com/YChsBwa.png), it's a screen of how Wavosaur implements it.

If we want a more in depth implementation that supports all of the loop point features, let me know and I can make a mockup of what I think it should look like, UI-wise.

**Comment by ornxka** [comment]
Sneedacity already has some UI code for ranges (clicking and dragging in the area above the track, where it has the time, will create a range in that span, play the track from the start of the range, and stop when it reaches the end). Loop ranges could just reuse that maybe.

**Comment by WhatsitTooya24** [comment]
> Honestly, you could just hijack the entire Labels UI for this

I think this is a good idea, the labels system already adds guides to help you re-select the label range. That would be useful when dealing with loop points.

> Sneedacity already has some UI code for ranges (clicking and dragging in the area above the track, where it has the time, will create a range in that span, play the track from the start of the range, and stop when it reaches the end). Loop ranges could just reuse that maybe.

This could work too, but it would have to be reworked a bit for sure. In both cases I'd say the loop point indicators (whatever system ends up getting decided upon) should probably be red, or some other color that stands out from the rest of the UI.

**Comment by EntranceJew** [comment]
Chiming in that this would be beyond useful, having to use waveosaur for a feature this trivial is a pain beyond belief. My only request is that it be handled in a way that I can import a ton of files and set their loop/cues per-track rather than per-project so that they can be batch exported. 

Also IIRC labels can support ranges of audio rather than just instants. Handling other more general types of cues would be a nice-to-have but handling the main case of loops is the broadest and most generally useful enhancement that's been missing, even if it's just a menu option that creates a label track named after the presently selected audio track with specially named labels. As long as the data exports and imports fine I can be at peace.

**Comment by ChucksConsulting** [comment]
Out of scope at the moment.
