### ISSUE TITLE
release workflows

### ISSUE THREAD

**Issue by Ckath** [Sneeds-Feed-and-Seed/sneedacity#145]
some automatically bumped releases would be nice. possibly also some more distros to build packages for since its now only ubuntu. debs should at least also be doable to add to the actions since someone already figured out how to do them.

besides that if it ever gets to a nice stable point (preferably after the whole conan/wxwidgets ordeal #47 is over with) also some 'stable' releases.

PS: just putting a list here for the nice to have extra actions:

- [ ] flatpaks
- [ ] snaps
- [ ] debs
- [ ] automate the arch binaries for https://github.com/Sneeds-Feed-and-Seed/sneed-arch-repo

**Comment by Ckath** [comment]
just putting a list here for the nice to have extra actions:

- [ ] flatpaks
- [ ] snaps
- [ ] debs
- [ ] automate the arch binaries for https://github.com/Sneeds-Feed-and-Seed/sneed-arch-repo

**Comment by ChucksConsulting** [comment]
This is too much work especially considering what a mess the CMake build system is. I think we should have one binary for all Linux distros. Something like what Firefox and Tor Browser do. Just distribute a folder with all the needed files minus what is expected to be on the average Linux desktop machine.
