### ISSUE TITLE
[Feature request] Pre-build binaries

### ISSUE THREAD

**Issue by GoatSee** [Sneeds-Feed-and-Seed/sneedacity#147]
Building is annoying
There was already an .Appimage by some anon and it worked fine, we should make one, they're very neat. 
Even though the project as of now mostly aims to appeal to tech-savvy /g/ users, we should consider making the program easy to install for tech illiterate by providing binaries, so you can just go to the website and click download button like you'd do with Audacity and other forks.

It'd be really cool to see people use sneedacity, instead of it being just a circlejerk for maintainers and for that i believe it is essential to provide binary releases
I'd say we probably want a windows installer, .rpm and .deb files and/or appimage for linux and whatever mac does
It would be also a good idea to consider making an arch package and perhaps a custom repository but that might be a bit far-fetched as of now; I also believe we should address the AUR issue, in an elegant manner obviously, so they dont just tell us to fuck off.
Here a picture because im used to including one in posts
![](https://files.catbox.moe/m05l5s.png)

**Comment by ChucksConsulting** [comment]
There's a whole section called "Pre-built binaries" in the front page. Idk what we could do to make it more visible.

**Comment by GoatSee** [comment]
huh? why are those zip files, i thought it was the source
either way, id be nice to do something about the AUR thing

**Comment by ChucksConsulting** [comment]
> huh? why are those zip files, i thought it was the source
> either way, id be nice to do something about the AUR thing

The PKGBUILD is in the repo. Idk what else we could do if the arch people are gonna take it down every time it gets posted in the AUR.
