### ISSUE TITLE
Implement online effects

### ISSUE THREAD

**Issue by weevilgit** [Sneeds-Feed-and-Seed/sneedacity#149]
One of the things that make Audacity/Sneedacity inferior to many other audio editing tools (e.g. Audition and Ableton) is the fact its effects are offline and destructible, meaning they have to be applied onto the sample, and completely alter it.

A much better approach is to create a pipeline in which the original sample stays the same as an input, and the output is calculated in real time. There are two ways to go about this, and below I give my opinion of which one is the best.

**First way: Mixer**
![](https://bedroomproducersblog.com/wp-content/uploads/2015/08/fl-studio-12-mixer.jpg)
Each fader above represents a bus. The bus takes any ammount of inputs, that are either the tracks (not in the picture), that are exactly like Sneedacity tracks, or other buses.
The bus then runs its input through its effects slots (top right,) top-down. Finally, it outputs the resulting audio to every bus it's connect to, and the master bus, that outputs to the speakers.

**Second way: Nodes (BEST ONE)**
![](https://i.stack.imgur.com/D3D7v.png)
Some of you might be familiar with two other FOSS projects that use nodes: Blender and Natron. Nodes, differently than mixers, have a **type system.** Every node has a type (input, throughput?, output,) and every node output also has a type (in the case of Blender, image, number, and misc iirc.)
This is much better because not a lot of audio projects have that, and the node system is very powerful if compared to online linear or offline systems.

If Sneedacity had a node system, it would be on par or superior to most, if not all audio software I work with, and I would definitely use it as an important part of my workflow.

**Reference implementations**
- Blender: FOSS, node system is image-based.
- Nattron: FOSS, also image-based.
- DaVinci Resolve: Proprietary, has nodes for image and audio.
- FL Studio's Patcher plugin: Proprietary, audio-based.

**Comment by nobuyukinyuu** [comment]
Processing sneed of each currently existing effect needs to be taken into consideration when attempting to render a real-time preview.  There's currently no equivalent to something like blender's "eevee" for this…

**Comment by ChucksConsulting** [comment]
Can you make a diagram of how the GUI would have to be modified to begin implementing this?

**Comment by ChucksConsulting** [comment]
Out of scope at the moment.
