### ISSUE TITLE
Small bug in Catalog feature/easter egg

### ISSUE THREAD

**Issue by EinBaum** [Sneeds-Feed-and-Seed/sneedacity#151]
@moxniso
I assume the Catalog feature should only open when you type SNEED all at once,
but it currently opens even when you type random stuff and it just happens to contain SNEED at some point
and then the thing could be opened by accident. (example: Special NEEDs person xd)

How to fix: Put an "else" and reset steps to 0 when the key doesn't match at https://github.com/Sneeds-Feed-and-Seed/sneedacity/pull/146/files#diff-d56dfa7da1fddbd0beab8ad122744455bfcd4d5c75160cb8c4614f9f542e9760R37

Also, the for-loop isn't needed at all (you only need to check the pressed key once)

THANKS!

**Comment by moxniso** [comment]
Thanks, going up now

**Comment by ChucksConsulting** [comment]
Should be fixed now
