### ISSUE TITLE
Thank you kind strangerino!! (ConfigDir bug)

### ISSUE THREAD

**Issue by EinBaum** [Sneeds-Feed-and-Seed/sneedacity#152]
@0kalekale
Redditor claims there is a bug in
https://github.com/Sneeds-Feed-and-Seed/sneedacity/pull/119/commits/51bf934a0a6fabeccf13dd35fb5b66b02dc325bd#diff-903e0551c858b5ffa955a67dc066ed90206e8e76be401634c802ed7f9ed8dd5bR637

Link: https://archive.is/mGPJw

**Comment by 0kalekale** [comment]
https://github.com/Sneeds-Feed-and-Seed/sneedacity/commit/be54fee24faee06e8e58d3d67b9c668dffda3736 already fixed this.

**Comment by EinBaum** [comment]
Thanks!
