### ISSUE TITLE
Migrating to the AGPL

### ISSUE THREAD

**Issue by ChucksConsulting** [Sneeds-Feed-and-Seed/sneedacity#156]
After re-consneedering it I think it would be better if we go with the AGPL because it prevents cloud offerings without releasing source code. That would make it harder for Muse to take our code and misuse it.
So if there are any objections please raise them now or I will be merging an AGPL PR tomorrow.

**Comment by meguminloli** [comment]
We can't relicense it. Muse states that Audacity is under GPL2, not GPL2 or later. We need to wait to see if they change the license upstream.

**Comment by ChucksConsulting** [comment]
> We can't relicense it. Muse states that Audacity is under GPL2, not GPL2 or later. We need to wait to see if they change the license upstream.

Oh, really? I thought they kept that clause
As I understand it we should still be able to offer a conveyed work with the new code under AGPL and the old code under GPL v2

**Comment by meguminloli** [comment]
We can add a new license. But the 99.9% of codebase will remain under GPL2. But we should wait for now to see if they change the license upstream.

**Comment by N-R-K** [comment]
I don't think you can mix other licenses with GPLv2.

https://www.gnu.org/licenses/rms-why-gplv3.html
> When we say that GPLv2 and GPLv3 are incompatible, it means there is no legal way to combine code under GPLv2 with code under GPLv3 in a single program. This is because both GPLv2 and GPLv3 are copyleft licenses: each of them says, “If you include code under this license in a larger program, the larger program must be under this license too.” There is no way to make them compatible.

**Comment by eylles** [comment]
Wasn't audacity gplv2 or later, also didn't muse group intend to migrate audacity to gplv3?

**Comment by N-R-K** [comment]
> Wasn't audacity gplv2 or later, also didn't muse group intend to migrate audacity to gplv3?

Although at the top it doesn't mention it, there'a an or later clause [here](https://github.com/audacity/audacity/blob/f2a0d918a2f62e8387bc1f1d3ca760b0c0ebd64c/LICENSE.txt#L313)

And according to [this](https://en.wikipedia.org/wiki/Affero_General_Public_License#Compatibility_with_the_GPL) GPLv3 (unlike v2) is compatible with AGPL.

Either ways, I don't think you can upgrade the ***existing codebase*** to AGPL, but you should be able upgrade it to GPLv3 which can be mixed with AGPL.

**Comment by georgebushfourtwenty** [comment]
Oh yes, get to work 4chads

**Comment by N-R-K** [comment]
> It says GPLv2 is compatible with AGPL v3

Where? This is what I'm reading

> In the Free Software Foundation's judgment, the added requirement in section 2(d) of Affero GPL v1 made it incompatible with the otherwise nearly identical GPLv2. That is to say, one cannot distribute a single work formed by combining components covered by each license.

**Comment by namazso** [comment]
there's also the problem that if upstream really manages to move to gplv3, the contributions in this repo also need to be CLA'd to move this to gplv3 too

**Comment by ChucksConsulting** [comment]
> ation's judgment, the added requirement in section 2(d) of Affero GPL v1 made it

The requirements added in the AGPL v1. Which was subsequently fixed in later versions like the AGPL such as v3, thus making it compatible with older versions of the GPL.

**Comment by ChucksConsulting** [comment]
> Where? This is what I'm reading

The "additional requirements" were added in the AGPL v1 and subsequently fixed in the AGPL v3, thus making it compatible with the GPL v3. What I'm not sure is if it also made it compatible with the GPL v2 with no later versions clause.
I sent an email to the FSF to clarify that. If they don't respond within the next week I'll send an email to rms.

> Although at the top it doesn't mention it, there'a an or later clause [here](https://github.com/audacity/audacity/blob/f2a0d918a2f62e8387bc1f1d3ca760b0c0ebd64c/LICENSE.txt#L313)

That doesn't count, it's just the little instructions on how to use the license.

**Comment by jobbautista9** [comment]
I think Audacity has explicitly (which is a requirement btw, do benefit from the "later version" clause) stated that the project is licensed under the GPLv2 **or later**, see this: https://www.audacityteam.org/about/license/

GPLv2+ code can't be unilaterally upgraded to GPLv3 without the permission of the author, but they can be mixed with GPLv3 code. The same with the AGPL. GPLv2+ can't be upgraded to AGPLv3 without the author's permission, but GPLv2+ code can be mixed with AGPLv3 code, and therefore the distribution as a whole would be under the AGPL.

So if we want to make use of the AGPL, we need to write original code in significant numbers and license them under the AGPL.

**Comment by ChucksConsulting** [comment]
> I think Audacity has explicitly (which is a requirement btw, to benefit from the "later version" clause) stated that the project is licensed under the GPLv2 **or later**, see this: https://www.audacityteam.org/about/license/
> 
> GPLv2+ code can't be unilaterally upgraded to GPLv3 without the permission of the author, but they can be mixed with GPLv3 code. The same with the AGPL. GPLv2+ can't be upgraded to AGPLv3 without the author's permission, but GPLv2+ code can be mixed with AGPLv3 code, and therefore the distribution as a whole would be under the AGPL.
> 
> So if we want to make use of the AGPL, we need to write original code in significant numbers and license them under the AGPL.

That just says what you must do to comply with the GPL license (whatever version it might be). It doesn't say "to comply with Audacity's license".

**Comment by ChucksConsulting** [comment]
> I think Audacity has explicitly (which is a requirement btw, to benefit from the "later version" clause) stated that the project is licensed under the GPLv2 **or later**, see this: https://www.audacityteam.org/about/license/
> 
> GPLv2+ code can't be unilaterally upgraded to GPLv3 without the permission of the author, but they can be mixed with GPLv3 code. The same with the AGPL. GPLv2+ can't be upgraded to AGPLv3 without the author's permission, but GPLv2+ code can be mixed with AGPLv3 code, and therefore the distribution as a whole would be under the AGPL.
> 
> So if we want to make use of the AGPL, we need to write original code in significant numbers and license them under the AGPL.

Yeah, I suppose that's good enough to pass off as consent. It would come down to whether we can prove that
- The website was written as such at this point in time
- The same person who wrote that was the person who wrote the code
- The code we used was also the code allegedly written by that person and published on the website

**Comment by binex-dsk** [comment]
or just ignore what the cringe license says and use the [based version of AGPL](https://agpl.plusnigger.swurl.xyz/)

**Comment by ChucksConsulting** [comment]
Maybe in the future.
