### ISSUE TITLE
Remove BLOAT

### ISSUE THREAD

**Issue by weevilgit** [Sneeds-Feed-and-Seed/sneedacity#164]
The following features are pretty much BLOAT, unless internals depend on them:
-  **Nyquist support:** An incomplete language with little to no programmers out there who actually know or use it. Outdated and superseded.
- **LADSPA plug-ins support:** Most if not all plug-ins nowadays are VSTs. LADSPA is superseded by LV2 anyway.
- **Modules:** [Almost undocumented,](https://manual.audacityteam.org/man/modules.html) there are three trivial examples online. No adoption whatsoever.
- **Pluck, Rhythm Track, and Risset Drum generators:** If the goal is to synthetize instruments, then it's much better to extend VST/AU/LV2 support to instruments (not only effects as it is the case right now.) These generators are too limited to turn Sneedacity into a synthetizer, but too different from sounds that have a technical application like Noise, Tones, and Chirps.

**Comment by Ckath** [comment]
I dont use any of these either, I think there was some talk about doing sneed modules though.

**Comment by eylles** [comment]
perhaps nyquist should remain, it seems like a candidate for sneedfication.

**Comment by parkbanks** [comment]
There would have to be evidence that no one uses Nyquist and the like. Removing would break continuity with Audacity, which should be the priority for now. At the very least, better alternatives should be developed before cutting out features and inconveniencing users.

**Comment by mariaWitch** [comment]
Extending VST/AU/LV2 to instruments seems like something that would be useful.

**Comment by mariaWitch** [comment]
Also, who in their right mind would want to use audacity as a kiosk application? Why were modules implemented and who were they even supposed to be meant for?

**Comment by MatthewTingum** [comment]
Ironically, it would be useful to have some telemetry to see if users are actually utilizing these things. I agree with @eylles. If we are to break something, we must provide an alternative at minimum. If support for a feature is to be discontinued, there must be ample notice. I suggest that that this issue overscopes. We have a `Discussions` tab for this. I think OP should come back with one bullet point at most and defend it *after* talking about it in discussion. There are things here I agree with. Lets see if the community agrees and break them in to manageable tasks.

IMO maintainer should close. All of these points will have their opportunity. Half of the community disagrees with *some* of the points. How are we to know which points the community disagrees with?

**Comment by EinBaum** [comment]
https://www.sneedsynth.club/
uses Nyquist and it shouldn't be removed because of that website

**Comment by BasedRimuru** [comment]
> The following features are pretty much BLOAT, unless internals depend on them:
> 
>     * **Nyquist support:** An incomplete language with little to no programmers out there who actually know or use it. Outdated and superseded.
> 
>     * **LADSPA plug-ins support:** Most if not all plug-ins nowadays are VSTs. LADSPA is superseded by LV2 anyway.
> 
>     * **Modules:** [Almost undocumented,](https://manual.audacityteam.org/man/modules.html) there are three trivial examples online. No adoption whatsoever.
> 
>     * **Pluck, Rhythm Track, and Risset Drum generators:** If the goal is to synthetize instruments, then it's much better to extend VST/AU/LV2 support to instruments (not only effects as it is the case right now.) These generators are too limited to turn Sneedacity into a synthetizer, but too different from sounds that have a technical application like Noise, Tones, and Chirps.

1. Nyquist is widely used and sneedsynth is a blessing
2. Removing LADSPA support would be nonsensical
3. Mod-script-pipes let you write plugins with any programming language
4. Removing native generators to use only VSTs would be a corporate move
5. There's absolute no advantages on doing any of these things

>Ironically, it would be useful to have some telemetry to see if users are actually utilizing these things

Telemetry shall never be re-implemented.
