### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by hugetits** [Sneeds-Feed-and-Seed/sneedacity#169]
**Is your feature request related to a problem? Please describe.**
Sneedacity is written in C++

**Describe the solution you'd like**
Rewrite in Rust

**Describe alternatives you've considered**
Kidnapping bruce3434

**Comment by EverlastingEndeavour** [comment]
Based alternative solution.

**Comment by jobbautista9** [comment]
Duplicate of #58

**Comment by hugetits** [comment]
> Duplicate of #58

Sorry, must have missed that! Though as you can see this feature is in high demand.
