### ISSUE TITLE
c++ Detoxing

### ISSUE THREAD

**Issue by MatthewTingum** [Sneeds-Feed-and-Seed/sneedacity#172]
```
C++ is a horrible language. It's made more horrible by the fact that a lot 
of substandard programmers use it, to the point where it's much much 
easier to generate total and utter crap with it. Quite frankly, even if 
the choice of C were to do *nothing* but keep the C++ programmers out, 
that in itself would be a huge reason to use C.
```
-- Loonix Himself

It would be quite the undertaking. What if you were faced with a pull request that replaced the whole sneed with C code. Would you listen? Would you allow a secondary *mater-c*? Perhaps instead if having a reasonable conversation you might insist that one of the github folk attempted to attack you with an ILLEGAL knife. Of course, this is not the case.

I propose a branch for c-sneedacity. Maybe we have a fork instead?

**Comment by georgebushfourtwenty** [comment]
*butter knife (yum)

Also, holy c or nothing.

**Comment by BasedRimuru** [comment]
Besides of my preference for C, Sneedacity has 800.000 lines of code, rewriting it in any other language would be a monumental task
