### ISSUE TITLE
Sneedacity release artwork

### ISSUE THREAD

**Issue by BasedRimuru** [Sneeds-Feed-and-Seed/sneedacity#174]
I plan to make an artwork for the official release of Sneedacity like OpenBSD does. It will be a parody of a famous pic with Sneed and some contributors. I have already decided the original art and it fits many people, but if it doesn't fit everyone I will have to prioritize the most active anons

If you want to be represented on the drawing, how should I draw you? People with anime profile pics are easy since I can draw the character, cookie will also appear and it's easy to draw him, but some people on the team I have no clue how to represent. Feel free to choose a character or to sadistically force me to draw a realistic person

If you don't want to be represented you can also say it here, but i swear it will be based

**Comment by sneedfVg** [comment]
thx my niggers

**Comment by parkbanks** [comment]
Draw me hyper-realistic. Or however you want. Also I could commission an artist for an additional piece or site banner.

**Comment by jobbautista9** [comment]
You can draw me using my profile picture. Or use my dog to represent me. Choose whichever is easier for you. :)
![pandakekok1](https://user-images.githubusercontent.com/73383951/125441215-a22cac83-09bd-4ce7-ba2f-e5cff4835c4b.jpg)
![pandakekok2](https://user-images.githubusercontent.com/73383951/125441225-6d4f1c7a-bbf5-4a74-ad28-f13f942a082c.jpg)

**Comment by binex-dsk** [comment]
draw me as my pfp

**Comment by eylles** [comment]
soon™
