### ISSUE TITLE
>no SNEED label

### ISSUE THREAD

**Issue by sonsofsneed3** [Sneeds-Feed-and-Seed/sneedacity#175]
what the chuck is your problem?

**Comment by formerlychuck** [comment]
sneed

**Comment by farmerchuck69** [comment]
@formerlychuck Thank you for being one of the Sneedposter's guys in Sneedacity, together we will kick out the Anti-Sneed anime cookieglowies and defend the original Sneedcontributors missions
God bless and God sneed
