### ISSUE TITLE
You vill eat ze bugs

### ISSUE THREAD

**Issue by Sneedfan115** [Sneeds-Feed-and-Seed/sneedacity#188]
Posted from my Schwabphone using Tapatalk pro

**Comment by binex-dsk** [comment]
eat the bugs

eat the grass

drink the leaves

**Comment by georgebushfourtwenty** [comment]
https://youtu.be/b7wogy34YZY

**Comment by realdep** [comment]
I will own nothing and i will be happy

**Comment by binex-dsk** [comment]
you WILL live in the pod

**Comment by BrotherIAmPinnedHere** [comment]
IT SNEEDS (although the amplify plugin from audacity 1.X is superior)

**Comment by ChucksConsulting** [comment]
Cleaning up issues.
