### ISSUE TITLE
Sneedsuite.org does not render proper if javascript is disabled

### ISSUE THREAD

**Issue by TheDuckWithAMonocle** [Sneeds-Feed-and-Seed/sneedacity#216]
Opening sneedsuite.org with a browser that has javascript leads to the website not rendering properly

**TO REPRODUCE**
1.) Disable javascript
2.)Go to sneedsuite.org
3.) ???
4.) Bugs profit.

**Comment by meguminloli** [comment]
This issue should be under sneedsuite.org repo.
