### ISSUE TITLE
The onion mirror should be a vanity onion sneedress

### ISSUE THREAD

**Issue by sneederiki** [Sneeds-Feed-and-Seed/sneedacity#230]
Use https://github.com/cathugger/mkp224o to generate a sneedy onion address

I can generate one and send the keys (gpg encrypted to https://github.com/Sneeds-Feed-and-Seed) if that would be more convenient

**Comment by mariaWitch** [comment]
Unfortunately one of the people hosting the mirror has stated that they use the link there for other things as well, so it would some effort on their end to get that setup. 

Sometime in the near future this may get addressed.

**Comment by binex-dsk** [comment]
^

My onion link is used for mirroring the rest of my site. However I can use a vanity onion URL and mirror the git subdomain on that new onion url, or just simply run it on that url, no subdomain

**Comment by sneederiki** [comment]
I prefer mirroring the git subdomain on a new onion url. It's feasible to generate vanity onions where the first 7 letters are fixed (this usually takes around a day) so sneedac*.onion?

**Comment by binex-dsk** [comment]
I've been generating onion urls starting with sneed for the past 14 hours and will probably do it for a couple more. we've gotten some good stuff like:

```
sneedban4govnhmeywpx5u3h2lxkk65br6m7v5otnrvrp7zvmydguyid.onion
sneedumdmymomvmadu2evvsspuoxbajsw64jat2chaexx354bsqpvfid.onion
sneedbaywyjbyo2xf7evosa3cjyatzudyrbxrbn4qrvnutdgwzcjcgad.onion
```

and some `sneedgay` one, if we get one that has `git` in it I'll use that one, otherwise I'll just use some of these. Though if we get `git`, then I'm just gonna use that without a subdomain.

**Comment by sneederiki** [comment]
Alright :) Use `sneedbay` or `sneedgay` if you don't get `sneedgit`.
