### ISSUE TITLE
sneeda songs

### ISSUE THREAD

**Issue by sneedjelly** [Sneeds-Feed-and-Seed/sneedacity#231]
i have never installed sneedacity or audacity but i'm assuming neither of them come preinstalled with sneeda songs

Here's Sound of Sneeda from simon and /g/arfunkel

Hello janny my old friend
I've come to fuck with you again
Because a sneedpost slowly rising
Left its seeds while I was browsing
And the sneedpost that was planted in my brain
Still remains
Within the sound of sneeda

In sneedless threads I scrolled alone
Boring posts of FAGMAN shills
'Neath the post of a wintard
I moved my fingers to post a bump
When my eyes were stabbed by the flash of a yellow light
That split the thread
And touched the sound of sneeda

And in the yellow thread I saw
Ten thousand jannies, maybe more
Jannies sucking without fucking
Jannies feeding without sneeding
Jannies banning posters who made them seethe
But no one dared
Disturb the sound of sneeda

"Janny", said I, you do not know
Sneeda like feeda grows
Hear my sneed that might feed you
Take my chuck that might sue you
But my chuck like a city slicker fell
And echoed in the wells of sneeda

And the jannies fuck and suck
In their fancy german car
And the sneedpost flashed out its warning
In the words that it was forming
And the sneed said the "The words of the prophets
Are written on the sneedpost threads
And sneedville roads
And whispered in the sound of sneeda

**Comment by guilletj** [comment]
Based
