### ISSUE TITLE
Sneedacity crashes upon opening.

### ISSUE THREAD

**Issue by brmonaghan** [Sneeds-Feed-and-Seed/sneedacity#241]
![image](https://user-images.githubusercontent.com/71337477/128248778-ebf17067-f4cd-45cb-9def-9e0d14aeaa28.png)

It appears that sneedacity crashes upon opening.

**Comment by Ckath** [comment]
would be helpful to see those files it mentions in the bug report, mainly log.txt.
is this from one of the prebuilt binaries the actions make or self compiled?

**Comment by brmonaghan** [comment]
> would be helpful to see those files it mentions in the bug report, mainly log.txt.
> is this from one of the prebuilt binaries the actions make or self compiled?

I will send to you. 
This is the self compiled program.

**Comment by brmonaghan** [comment]
[Sneedacity_dbgrpt-8968-20210804T161413.zip](https://github.com/Sneeds-Feed-and-Seed/sneedacity/files/6938643/Sneedacity_dbgrpt-8968-20210804T161413.zip)

**Comment by Ckath** [comment]
sad violin music:
```
$ cat log.txt
# empty file
```

if you built it yourself I assume its not a release build, what does it say up to crashing when you launch sneedacity from a terminal?

**Comment by brmonaghan** [comment]
I will try to launch from Command prompt.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by brmonaghan** [comment]
Still building at the moment with new code.

**Comment by Ckath** [comment]
no rush, at conan removal there were some weird linking issues where windows builds would go through but dlls would end up in the wrong place. I'm not very familiar with the windows build process so if it complains about missing dlls not much I can help with.

**Comment by brmonaghan** [comment]
Ok thanks!

**Comment by brmonaghan** [comment]
Its almost done.

**Comment by brmonaghan** [comment]
![image](https://user-images.githubusercontent.com/71337477/128360682-76cbcf66-4098-49e9-95a9-54f97b251fe2.png)
WORKED! Thanks!
Closing

**Comment by Ckath** [comment]
anything you did this time to make it work over the last build?
for future reference sake

**Comment by brmonaghan** [comment]
Just removed and rebuilt the code from the ground up.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
