### ISSUE TITLE
Compiling project on MacOS 11 fails. No member named 'ptrdiff_t' in the global namespace

### ISSUE THREAD

**Issue by sbritorodr** [Sneeds-Feed-and-Seed/sneedacity#251]
**Describe the bug**
Cannot compile the program using XCode Version 12.5.1 (12E507). It outputs 11 errors, mostly are "No member named 'ptrdiff_t'" or similar bugs.

[log.txt](https://github.com/Sneeds-Feed-and-Seed/sneedacity/files/7024404/log.txt)
 file attached

**To Reproduce**
1. Make all steps for MacOS in the [Build Instructions](https://github.com/Sneeds-Feed-and-Seed/sneedacity/blob/master/BUILDING.md)
2. Build the program in XCode with CMD+B
3. Errors

**Additional information:**
 - OS: MacOS Big Sur 11.4
 - Don't know how can I see the sneedacity version, but It's the same as [my fork](https://github.com/sbritorodr/sneedacity) 
 - XCode 12.5.1
 - CMake 3.21.1
 - 

**Screenshots**
<img width="844" alt="Screenshot 1" src="https://user-images.githubusercontent.com/36245871/130301722-26bc6392-9054-46b9-8528-829d495d6e7e.png">
<img width="543" alt="Screenshot 2" src="https://user-images.githubusercontent.com/36245871/130301931-1dd7f6e9-f165-4393-84d9-1c31c465bc78.png">

**Comment by Ckath** [comment]
seems like some macos specific library install loction mess. you either dont have c++ stuff installed/enabled or its in a place it doesnt expect it, could be /usr/local/ or something. but also very possible the specific library version or clang messes something up here. I just dont know anything about macos and no one ever builds it on there. 
as a sanity check could you try building with gcc instead? and do be aware there are also [binaries(which might even work)](https://github.com/Sneeds-Feed-and-Seed/sneedacity/suites/3512220081/artifacts/83792823)

**Comment by sbritorodr** [comment]
I've installed the binaries for macos, but for some reason it doesn't start up. That's why I'm trying to manually compile it.
[Sneeedacity Binaries.txt](https://github.com/Sneeds-Feed-and-Seed/sneedacity/files/7025132/Sneeedacity.Binaries.txt)

Okay, I'm going to try installing those libraries if isn't installed or try using gcc.

I know, compiling in macos is a mess. If I manage to succeed, I'll add all the steps I made to [sneedacity/BUILDING.MD](https://github.com/sbritorodr/sneedacity/blob/master/BUILDING.md).

**Comment by Ckath** [comment]
> I know, compiling in macos is a mess. if I finally get to compile the program, I'll add all the steps I made to sneedacity/BUILDING.MD.

that'd be great, good luck

**Comment by ChucksConsulting** [comment]
I think it's better that we discontinue the Mac builds untill someone with a Mac is willing to maintain that version. I don't think trying to debug on a headless VM is a viable option and I don't have the hard drive space to keep a MacOS VM on my local machine.

**Comment by sbritorodr** [comment]
Yes. I've tried to compile it in my MacBook Air. That was a huge mistake.
