### ISSUE TITLE
sneedacity as an lv2/vst plugin

### ISSUE THREAD

**Issue by bushcountysheriff** [Sneeds-Feed-and-Seed/sneedacity#254]
plzzzzzzzzzzzzz

**Comment by Ckath** [comment]
did audacity have any chance of efforts made towards this?
sounds like a pretty high bar thing. I doubt wxwidgets is the thing you want as ui for being embeddable in other applications as plugins

**Comment by georgebushfourtwenty** [comment]
I probably should've named the issue "rewrite in juce".
Surge (which uses cairo) is doing it as well.
Yeah it is going to take a lot of work.

**Comment by Ckath** [comment]
> Yeah it is going to take a lot of work.

you start :^)
I'll review your pr when it's ready

**Comment by ChucksConsulting** [comment]
This feature is out of scope, at least until there is enough manpower to improve upon Audacity and not just track upstream changes.
