### ISSUE TITLE
sneed

### ISSUE THREAD

**Issue by binex-dsk** [Sneeds-Feed-and-Seed/sneedacity#261]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]
 - Version [e.g. Sneedacity 2.5.1]
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**

**Comment by nonetrix** [comment]
sneeded

**Comment by ChucksConsulting** [comment]
Cleaning up issues.

**Comment by nonetrix** [comment]
sneeded
