### ISSUE TITLE
Death to open source

### ISSUE THREAD

**Issue by ghost** [Sneeds-Feed-and-Seed/sneedacity#265]
Death to people who like the simpsons . 
The simpsons is a stupid mainstream propaganda cartoon used to promote the idiots and losers.
 Death to "universities". Death to people who use the stupid "titles" with names. Death to the stupid and garbage so called "health sector". Death to the open source mindset.

**Comment by 2ro** [comment]
lolwut

**Comment by Sneethe** [comment]
Ran out of schizo feed?

**Comment by Realswitzer** [comment]
what no bitches does to a mf

**Comment by kerme0w** [comment]
fuck off
