### ISSUE TITLE
A SNEEDFUL LICENSE

### ISSUE THREAD

**Issue by binex-dsk** [Sneeds-Feed-and-Seed/sneedacity#266]
**Is your feature request related to a problem? Please describe.**
WE NEED A SNEEDFUL LICENSE

**Describe the solution you'd like**
[Giant Penis License](https://licenses.swurl.xyz), but sneedful. Keep the giant penis but add a giant Sneed, and make some sneedful changes

**Describe alternatives you've considered**

**Additional context**

**Comment by Pythone** [comment]
I will make sure that there's a good license, but we cannot have a giant #####
It is a Sneed-only license.
I came up with this name: "the farmer's license".

**Comment by binex-dsk** [comment]
Giant sneed license has been made

**Comment by Realswitzer** [comment]
combine GPL and GSL, easy fix with getting the "#####" and the Sneed

**Comment by ChucksConsulting** [comment]
People have made enough fun of us for editing the README already, all further efforts should be focused on providing an alternative to Audacity that doesn't phone home, and not drama.
