### ISSUE TITLE
Built executable segfaults on Debian 11

### ISSUE THREAD

**Issue by bootmii** [Sneeds-Feed-and-Seed/sneedacity#267]
**Describe the bug**
When built on Debian 11, the executable `sneedacity` segfaults on launch.

**To Reproduce**
1. Install the required packages
2. Try to run Cmake.
3. The source tree doesn't have a `sneedacity` *sub*directory, guess we're using .. instead.
4. Run `make`
5. Run `bin/Debug/sneedacity`
6. See a "segmentation fault" error

**Expected behavior**
1. You wouldn't be telling us to refer to `../sneedacity`, which doesn't exist once we cd into `build`.
2. I have all the dependencies, and all the warnings about how wxWidgets shouldn't be using GTimeVal and all the deprecated declarations shouldn't matter.
3. The binary doesn't segfault on launch
**Screenshots**

**Additional information (please complete the following information):**
 - OS: Debian 11 Bullseye
 - Version: Sneedacity 3.x, I think I cloned it
 - Sound Device: ALSA/PulseAudio on an Intel HD Audio chipset

**Additional context**

**Comment by ChucksConsulting** [comment]
I was able to confirm this bug on a fresh amd64 Debian VM.

**Comment by ChucksConsulting** [comment]
It happens inside the function Pa_Initialize() called in the line `PaError err = Pa_Initialize();` of the file AudioIO.cpp.
We need to find out why Portaudio is segfaulting.

**Comment by ChucksConsulting** [comment]
Should be fixed in commit 9bf36c76e852a9ef8e7c06740ea9e1cf9e54c7d7. Please re-open if the error persists.
