### ISSUE TITLE
Error 2 when compiling (void linux i686)

### ISSUE THREAD

**Issue by longboarder241** [Sneeds-Feed-and-Seed/sneedacity#275]
After following the instructions everything seems correct until I run into this error when compiling;
[  0%] Building C object cmake-proxies/wxWidgets/wxwidgets/libs/CMakeFiles/wxregex.dir/__/src/regex/regcomp.c.o
[  0%] Building CXX object libraries/lib-utility/CMakeFiles/lib-utility.dir/MemoryX.cpp.o
error: error: Connection to server timed outConnection to server timed out

make[2]: *** [libraries/lib-utility/CMakeFiles/lib-utility.dir/build.make:76: libraries/lib-utility/CMakeFiles/lib-utility.dir/MemoryX.cpp.o] Error 2
make[2]: *** [cmake-proxies/wxWidgets/wxwidgets/libs/CMakeFiles/wxregex.dir/build.make:76: cmake-proxies/wxWidgets/wxwidgets/libs/CMakeFiles/wxregex.dir/__/src/regex/regcomp.c.o] Error 2
make[1]: *** [CMakeFiles/Makefile2:1052: cmake-proxies/wxWidgets/wxwidgets/libs/CMakeFiles/wxregex.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:2265: libraries/lib-utility/CMakeFiles/lib-utility.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
Is there something wrong I'm doing? Any feedback would be great!
[  0%] Building C object cmake-proxies/wxWidgets/wxwidgets/libs/CMakeFiles/wxregex.dir/__/src/regex/regcomp.c.o
[  0%] Building CXX object libraries/lib-utility/CMakeFiles/lib-utility.dir/MemoryX.cpp.o
error: error: Connection to server timed outConnection to server timed out

make[2]: *** [libraries/lib-utility/CMakeFiles/lib-utility.dir/build.make:76: libraries/lib-utility/CMakeFiles/lib-utility.dir/MemoryX.cpp.o] Error 2
make[2]: *** [cmake-proxies/wxWidgets/wxwidgets/libs/CMakeFiles/wxregex.dir/build.make:76: cmake-proxies/wxWidgets/wxwidgets/libs/CMakeFiles/wxregex.dir/__/src/regex/regcomp.c.o] Error 2
make[1]: *** [CMakeFiles/Makefile2:1052: cmake-proxies/wxWidgets/wxwidgets/libs/CMakeFiles/wxregex.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:2265: libraries/lib-utility/CMakeFiles/lib-utility.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by fastpain** [comment]
What OS?

**Comment by Ckath** [comment]
since your make is saying `error: error: Connection to server timed outConnection to server timed out`, something comes to mind about the current state of wxwidgets compiling pulling in the source through a git clone, or other means

**Comment by longboarder241** [comment]
> What OS?

Void, yeah the one that threw a hissy fit when people wanted sneedacity in their repos

**Comment by longboarder241** [comment]
Well, it works now so no need to worry anymore

**Comment by Ckath** [comment]
grand
