### ISSUE TITLE
Lastest Windows Builds (32+64) shipped in debug, not release (suspected)

### ISSUE THREAD

**Issue by kagrith** [Sneeds-Feed-and-Seed/sneedacity#277]
When attempting to run the newest binaries at time of writing, several DLLs appear to be missing.
"VCRunTime140D
MSVCP140D
ucrtbased
vcruntime140D"
Application does not launch.

**To Reproduce**
1.  Download Latest Windows Release
2. Extract and Run
3. See error

**Expected behavior**
Program launch without dependencies which seem to not be listed in readme.
(its possible i missed them, with my aversion to walls of text, but does not seem to be any idication of what i could be missing.

**Additional information (please complete the following information):**
 - OS: Win10 10.0.19043 Build 19043
 - Version 20220326

**Additional context**

Per:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/06b66cae-d010-441d-bc72-64a8c7cd65bc/missing-vcruntime140ddll-and-ucrtbaseddll?forum=visualstudiogeneral

Suspected issue is that was compiled in debug, not release.

**Comment by Ckath** [comment]
for some reason the debug is set in 4 places, with different capitalization. I've changed it all there to `release`. if the pr does succesfully build, let me know if that fixes it before merge. cant test windows systems atm

**Comment by kagrith** [comment]
Looks like build was successful, but it doesn't seem to be exporting files
I can test.
If you could advise or link the files, that would be great, and I can test.

**Comment by Ckath** [comment]
it is a bit hidden I suppose, they're on the summary of the builds/actions because github thought that'd be a clear place to put them
https://github.com/Sneeds-Feed-and-Seed/sneedacity/actions/runs/2286577853
![image](https://user-images.githubusercontent.com/15038414/167311198-e837433c-198a-44f9-b397-19fa2a5ac4f0.png)
the windows ones should be similar zip files to what you usually use from the releases

**Comment by kagrith** [comment]
ahhh! thank you much.
I ended up looking for the builds in another spot and ended up with a build from 2021, thus my confusion and clerification request.

I did get this build working though, without issue. simple unpack and run,
So you should be able to merge without issue?
Cheers!

**Comment by Ckath** [comment]
cheers
