### ISSUE TITLE
Error when running pkgbuild on artix (ffmpeg5)

### ISSUE THREAD

**Issue by longboarder241** [Sneeds-Feed-and-Seed/sneedacity#281]
After following the steps for doing a makepkg my install stalls at 74% with this message;
<command-line>: warning: extra tokens at end of #undef directive
make[2]: *** [src/CMakeFiles/Sneedacity.dir/build.make:173: src/CMakeFiles/Sneedacity.dir/SneedacityApp.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:3001: src/CMakeFiles/Sneedacity.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Any help would be great

**Comment by Ckath** [comment]
not really a fix to build it on 4.4, its going to have to just be beat into compiling.
I'll try messing with the unmerged pr made to audacity

**Comment by 4Kirb** [comment]
Yeah, I have a segfault on the compiled binary any ways, although I have no idea where to start with that.

**Comment by Ckath** [comment]
the audacity source and the sneedacity one arent as compatible as they used to anymore with audacity having made the continuous awful effort to move random things into `libraries/`, was trying to just upgrade all the ffmpeg related parts and slap the pr ontop but its not working out quite as well as I hoped.
the futile effort so far https://github.com/Ckath/sneedacity/tree/ffmpeg5
might look at it again when sober

**Comment by 4Kirb** [comment]
Not entirely sure how audacity is put together/designed, so I'm afraid I can't really help.

**Comment by Ckath** [comment]
the gist of it is the same as roughly all issues before it that involved upstream or wild fixes:
the code 'compiles', however due unknown knowledge of how cmake works or how the project builds it fails at linking.
the conan removal stuff stayed at this stage for ages but at that time there were more people with better ideas. 
an alternative would be to look into why the current ffmpeg related code cant deal with ffmpeg5 and slowly nudge it towards wanting to compile under ffmpeg5, what I've done currently is just take the audacity code with all the new ffmpeg interaction and try to hammer it into sneedacity which is many codebase redoals behind of it at this point. your messing around with the source until it compiles is going to be as good as mine.

I am not a c++ dev,
I'm not very familiar with cmake,
to this day I have no clear idea of what causes it to build and links the way it does

**Comment by Ckath** [comment]
insult to injury
![image](https://user-images.githubusercontent.com/15038414/175993990-b59298c6-ab6e-4acb-849d-8f9adf617255.png)
