### ISSUE TITLE
Contingency plan if repo baleeted

### ISSUE THREAD

**Issue by koyafish** [Sneeds-Feed-and-Seed/sneedacity#29]
Might want to mirror repo on another location in case of buttpain

**Comment by jshield** [comment]
yeah given the AUR package got "baleeted".

**Comment by BasedRimuru** [comment]
Gitlab would be the best choice in my opnion

**Comment by formerlychuck** [comment]
added a backup on gitlab that will mirror this repo
https://gitlab.com/sneeds-feed-and-seed/sneedacity

**Comment by koyafish** [comment]
sneed

**Comment by binex-dsk** [comment]
gitlab might janny it too, heres a funny mirror on my self hosted gitea instance so no jannying unless the feds fuck me lel https://git.funny.cl/Sneeds-Feed-and-Seed/sneedacity
