### ISSUE TITLE
 Death to those monkeys who made that stupid garbage cartoon " the simpsons"

### ISSUE THREAD

**Issue by ghost** [Sneeds-Feed-and-Seed/sneedacity#292]
Death to those monkeys who made that stupid garbage cartoon " the simpsons" . Death to every idiot who likes that trash. Death to them for promoting. 
Death to "universities"[*dumpster*]. Death to open source. Death to garbage mainstream propaganda slaves. Death to you every idiot who uses those stupid  childish and disgusting words before meentioning first names devs. Hope they have a tragic life and painful death.

**Comment by AchmadFathoni** [comment]
Well, at least one of your wish comes true. This project is dead.
