### ISSUE TITLE
Doesn't display correctly on Hidpi distros

### ISSUE THREAD

**Issue by ChucksConsulting** [Sneeds-Feed-and-Seed/sneedacity#31]
The Ubuntu Audacity package works fine, haven't tried building from git.
https://s1.desu-usergeneratedcontent.xyz/g/image/1625/54/1625546555528.png

**Comment by BasedRimuru** [comment]
Does this still happens? Can you build with Audacity upstream to see if the bug is present?

**Comment by ChucksConsulting** [comment]
> Does this still happens? Can you build with Audacity upstream to see if the bug is present?

Upstream has it too, yeah. Only works correctly on Ubuntu provided package.

**Comment by ChucksConsulting** [comment]
I mean, "correctly" is relative. Both look like shit, but the left one seems to at least make an effort to scale rather than just blowing up the fonts.

**Comment by ChucksConsulting** [comment]
Unfortunately at the moment there are more important issues. But this will have to be fixed at some point.
