### ISSUE TITLE
Sneedacity lacking the standard audio generators and filters

### ISSUE THREAD

**Issue by ChucksConsulting** [Sneeds-Feed-and-Seed/sneedacity#32]
Maybe because they are implemented as Nyquist plugins or something. Could be because we forked from an alpha.
IMO the fastest way to diagnose would be to find at what point in the commit history it stopped working.
Possibly try to build different versions of Audacity because we squashed the commit history from 3.0.2 to 3.0.4 (when the fork was made) so if it doesn't work in Audacity either it won't be possible to check at what point it stopped working.

**Comment by BasedRimuru** [comment]
I built the latest audacity and it doesn't work on their version too, probably it has something to do with debug builds or alpha

**Comment by ChucksConsulting** [comment]
It's working on the latest Audacity release. What was the commit this was forked from anyway?

**Comment by ChucksConsulting** [comment]
This is the first commit that makes the filters dissapear
https://github.com/Sneeds-Feed-and-Seed/sneedacity/commit/34bf107c04bb528e423d9de5033606beb646151e

**Comment by Furitenman** [comment]
> 
> 
> This is the first commit that makes the filters dissapear
> [34bf107](https://github.com/Sneeds-Feed-and-Seed/sneedacity/commit/34bf107c04bb528e423d9de5033606beb646151e)
>
Easiest way to fix this (I think) would be to get a new branch, revert this commit and slowly start changing the name until something breaks.

**Comment by nulldg** [comment]
Easiest fix is revert that commit. Don't CTRL+F the entire codebase like every other fork did, because that shit broke them too. All the environment vars are now named differently and the user's config (from an older install of Audacity) is no longer reused, and causes unholy messes in the code which the commit owner never actually bothered to manually review.

Refactor it incrementally by editing labels, titles, and documentation first (all the stuff the end-user sees), followed by internal changes.
Audacity has FAR too much technical debt to be doing these kinds of brute automated changes.

**Comment by Ckath** [comment]
I did a blanket sed for all AUDACITY Audacity and audacity mentions that were still in the source and this also doesnt fix the effects and generate menus. even though the offending commit seems to also just be a big audacity -> sneedacity rename.

is it somehow related to external factors?

**Comment by ChucksConsulting** [comment]
> Don't CTRL+F the entire codebase like every other fork did, because that shit broke them too.
> Ignoring the fact that all the environment vars are now named differently and the user's config (from an older install of Audacity) is no longer reused, the replacement potentially caused an unholy mess in the code which the commit author never actually bothered to manually check.
> 
> Refactor it incrementally by editing labels, titles, and documentation first (all the stuff the end-user sees), followed by internal changes.
> Audacity has FAR too much technical debt to be doing these kinds of brute automated changes.

Yeah, that will have to be the way forward. I'll revert the changes made on that commit and see what happens.

**Comment by Ckath** [comment]
\>looking at the other renamed forks
\>they didnt even bother renaming
great times all around

**Comment by Ckath** [comment]
deemed as fixed for now until upstream solution comes along
