### ISSUE TITLE
Import issues from the main fork

### ISSUE THREAD

**Issue by Furitenman** [Sneeds-Feed-and-Seed/sneedacity#35]
https://github.com/IQAndreas/github-issues-import

Despite being raided, there's probably a lot of issues that need fixing and could give Sneedacity an edge over all the other shitty forks. There's a github version, but only works for if you're the owner of both repositories.

**Comment by ChucksConsulting** [comment]
I don't think it's worth it to import issues. Browsing there and manually copying anything important is probably good enough.

**Comment by ChucksConsulting** [comment]
Can you close this issue? @Ckath @meguminloli

**Comment by ChucksConsulting** [comment]
Closing since we already came up with enough ideas to progress on our own.
