### ISSUE TITLE
Can't find sneedacity on main github search

### ISSUE THREAD

**Issue by koyafish** [Sneeds-Feed-and-Seed/sneedacity#37]
https://github.com/search?q=sneedacity&type=

**Comment by koyafish** [comment]
Possible to rename as Sneed Suite?

**Comment by koyafish** [comment]
Not sure why it's doing that

**Comment by Furitenman** [comment]
They probably flagged it. I would rename it to Sneeaudicity. Maybe also check if the org wasn't flagged.

**Comment by hey-ram** [comment]
I don't think forked repositories are visible in search.

**Comment by koyafish** [comment]
> I don't think forked repositories are visible in search.

Yes, just checked that this is true. See https://stackoverflow.com/questions/19741575/search-a-forked-repo-in-github

**Comment by meguminloli** [comment]
> https://github.com/search?q=sneedacity&type=

looks like you can find the issues from this repo, but you can't find the repo

**Comment by koyafish** [comment]
Not sure how this can be fixed

**Comment by Furitenman** [comment]
https://github.com/search?q=sneedacity+fork%3Atrue

**Comment by jshield** [comment]
early enough to create a new repo without preserving the issues IMHO.

**Comment by cmdrkotori** [comment]
If you get it to work let me know how. I'm dealing with the same issue.

**Comment by cmdrkotori** [comment]
Well I fixed it for one of my repos.
1. Create an organization
2. Push to it
3. Leave a notice/issue on the old repo
4. Archive it the old repo

**Comment by formerlychuck** [comment]
posted in another issue but I have made a request to detach this as a fork of audacity which I think will fix it

**Comment by formerlychuck** [comment]
Sneedacity has been detached and is now searchable
