### ISSUE TITLE
CentOS/Fedora .rpms?

### ISSUE THREAD

**Issue by gamelone** [Sneeds-Feed-and-Seed/sneedacity#41]
Any hope of official rpms for both CentOS and Fedora?

![sneedoran](https://user-images.githubusercontent.com/81271349/124592101-160f6600-de2b-11eb-8bd9-5f29e2e45d66.png)

**Comment by meguminloli** [comment]
Depends on what Fedora does to generate builds especially for their libraries. Mainstream Audacity uses Appimages for all distros.  https://github.com/diddlesnaps/audacity/blob/master/snap/snapcraft.yaml
this is the file used for creating snaps from Audacity. Maybe Flatpak packages would be a better choice than distro specific binaries.

**Comment by ChucksConsulting** [comment]
is there a checkinstall equivalent for Fedora?

**Comment by chuck-sneed** [comment]
some anon suggested COPR (https://copr.fedorainfracloud.org/), which it's integrated into `dnf` 

I suggest using OBS (https://openbuildservice.org/) for various distro packages, including fedora

**Comment by ChucksConsulting** [comment]
At the moment the regular binaries will have to do, unless somebody wants to work on it.
