### ISSUE TITLE
Sneedacity Windows installer

### ISSUE THREAD

**Issue by Furitenman** [Sneeds-Feed-and-Seed/sneedacity#42]
Finally got it to compile. Someone else with windows test it as well. Thanks to @meguminloli to make another version so I could compare it.
[sneedacity.zip](https://github.com/Sneeds-Feed-and-Seed/sneedacity/files/6770131/sneedacity.zip)

**Comment by Furitenman** [comment]
Submitted to choco btw.

**Comment by DevElonCoin** [comment]
Sneedpilled

**Comment by nulldg** [comment]
Hurry up and make an actual release you fucking onions, and make sure to label it correctly goddamn

If you want them city slickers to use this fork then you better make it accessible to them

**Comment by meguminloli** [comment]
> Hurry up and make an actual release you fucking onions, and make sure to label it correctly goddamn
> 
> If you want them city slickers to use this fork then you better make it accessible to them

The maintainer of this project has been AFK for some hours. Wait until he approves workloads.

**Comment by BasedRimuru** [comment]
I don't think we can make an actual release yet, because we forked from the alpha build, there's many bugs around

**Comment by Furitenman** [comment]
> 
> 
> I don't think we can make an actual release yet, because we forked from the alpha build, there's many bugs around
>
True, but it's a start. Also the inno script in cmake is botched, so that lead me to discover that we may need to rewrite the whole thing.

**Comment by formerlychuck** [comment]
I'll look into a release tonight

**Comment by meguminloli** [comment]
> I'll look into a release tonight, even if it's kind of broken, better than nothing

You should probably debug GitHub Actions now.

**Comment by Furitenman** [comment]
Here are some recent windows builds (not *the* latest since someone committed while I was creating the installer) in case anyone needs them. Feel free to test them.
[sneedacity-3.0.4-alpha-20210707.exe.zip](https://github.com/Sneeds-Feed-and-Seed/sneedacity/files/6780071/sneedacity-3.0.4-alpha-20210707.exe.zip)
[sneedacity-3.0.4-alpha-20210707-x64.exe.zip](https://github.com/Sneeds-Feed-and-Seed/sneedacity/files/6780073/sneedacity-3.0.4-alpha-20210707-x64.exe.zip)

**Comment by ChucksConsulting** [comment]
Can you close this issue? @meguminloli

**Comment by ChucksConsulting** [comment]
Windows builds work now.
