### ISSUE TITLE
Actions didn't start even if the script is working

### ISSUE THREAD

**Issue by meguminloli** [Sneeds-Feed-and-Seed/sneedacity#44]
**Describe the bug**
Looks like Github is scuffed once again and it doesn't start actions.
Maybe we should nuke this fork and start a real repository so people can find us too.

**Comment by Furitenman** [comment]
I agree, maybe even make an organization to keep stuff simplified.

**Comment by BasedRimuru** [comment]
Wouldn't make any sense to nuke the repo now, and Sneeds-Feed-and-Seed is an organization

**Comment by meguminloli** [comment]
We can copy the contents from this repo. Just change the repo from a fork into a standalone repo.
Looks like you can't even find it if it's a fork.

**Comment by BasedRimuru** [comment]
Ahh now I see, that isn't a bad idea actually

**Comment by ChucksConsulting** [comment]
It would lose all the stars it already has. But maybe that doesn't matter idk.

**Comment by meguminloli** [comment]
> It would lose all the stars it already has. But maybe that doesn't matter idk.

Looks like we don't need to delete it, but beg to Github Support .
https://stackoverflow.com/a/44140289

**Comment by formerlychuck** [comment]
I guess I will try github support

**Comment by formerlychuck** [comment]
I have made the request, and also actions should be enabled

**Comment by formerlychuck** [comment]
Sneedacity is detached
