### ISSUE TITLE
rewrite it in rust

### ISSUE THREAD

**Issue by fanninpm** [Sneeds-Feed-and-Seed/sneedacity#58]
**Is your feature request related to a problem? Please describe.**
C and C++ are old languages that are riddled with memory safety footguns. This can result in corrupted files, for example.

**Describe the solution you'd like**
Rewriting it in Rust would avoid many memory safety issues, and would also bring other benefits, such as integrated dependency management with Cargo.

**Describe alternatives you've considered**
Of course, leaving the current implementation as is would make this codebase _that_ much more similar to \*\*d\*c\*t\*'s codebase.

**Additional context**
[🦀🦀🦀](https://youtu.be/LDU_Txk06tM)

**Comment by binex-dsk** [comment]
holy real

**Comment by shengslogar** [comment]
wat

**Comment by nek0bit** [comment]
Rust is the most powerful programming language

**Comment by fanninpm** [comment]
@nek0bit 

+++++ +++++ [->++ +++++ +++<] >++++ +.<++ +[->+ ++<]> ++.<+ +++++ +++[-
>---- ----- <]>-- -.<++ +++++ ++[-> +++++ ++++< ]>++. <+++[ ->--- <]>--
---.. +++++ +++.+ +++++ .<+++ +++++ +[->- ----- ---<] >--.< +++++ ++++[
->+++ +++++ +<]>+ +++++ ++.<+ ++[-> ---<] >-.++ ++++. <++++ +++++ [->--
----- --<]> ----. <++++ ++++[ ->+++ +++++ <]>++ ++++. +++++ ++++. +++.<
+++[- >---< ]>--. +++++ +++.+ ++++. <++++ +++++ [->-- ----- --<]> ---.<
+++++ +++[- >++++ ++++< ]>+.< +++++ +++[- >---- ----< ]>-.< +++++ +++[-
>++++ ++++< ]>++. <++++ [->++ ++<]> .<+++ +[->- ---<] >-.++ .++++ ++++.
----- -.<++ +[->+ ++<]> +++++ +.<++ +++++ ++[-> ----- ----< ]>--- .<+++
+++++ +[->+ +++++ +++<] >++.- ---.- -.--- ----- .<+++ +[->+ +++<] >++.<
+++[- >---< ]>--- ---.- --.<+ ++[-> +++<] >++++ .<+++ [->-- -<]>- ---.<
+++++ +++[- >---- ----< ]>--- --.<+ +++++ ++[-> +++++ +++<] >++++ +++++
+++++ +.-.< +++++ +++[- >---- ----< ]>--- ----- ----- -.<++ +++++ +[->+
+++++ ++<]> +++++ +++++ ++.-- -.+++ ++.-- ----- --.<+ +++++ ++[-> -----
---<] >---- -.<++ ++[-> ++++< ]>+++ +.-.<

**Comment by nek0bit** [comment]
@fanninpm I do not speak in ascii sword, sorry.

**Comment by arivega** [comment]
@fanninpm lol no

**Comment by mvasilkov** [comment]
Rewrite in Turbo Pascacal is currently underway, so Rust will have to wait.

**Comment by TechGuyOnTGB** [comment]
Nah let's rewrite in ziglang 😀

https://ziglang.org/

**Comment by alonsobustamante98** [comment]
Yeah the whole codebase is a mess with like a million LOC so we need to rewrite a lot.
BUT I think we should stick with WxWidgets. It would simplify any transition we decide to move towards.
https://en.wikipedia.org/wiki/List_of_language_bindings_for_wxWidgets
No Rust, it seems.
Let's revisit this at a later date anyway. First we need to achieve complete feature parity.

**Comment by binex-dsk** [comment]
does Qt have rust bindings? if so, after we fix all issues we have, me and some other Qt chads rewrite it in Qt, then we switch to the rust bindings. simple!

**Comment by fanninpm** [comment]
> does Qt have rust bindings?

[Dpes this count?](https://rust-qt.github.io/qt/)

**Comment by binex-dsk** [comment]
> > does Qt have rust bindings?
> 
> 
> 
> [Does this count?](https://rust-qt.github.io/qt/)

i suppose, time to rewrite it in Qt with Rust

**Comment by namazso** [comment]
why not rewrite Qt in rust too?

**Comment by fanninpm** [comment]
> why not rewrite Qt in rust too?

See also: https://github.com/sixtyfpsui/sixtyfps

**Comment by binex-dsk** [comment]
TRUE, we need to rewrite all the libraries sneedacity uses (INCLUDING CMAKE) in Rust. That way we truly will be different from a\*d*c\*ty and no segfaults and security issues!

**Comment by alonsobustamante98** [comment]
What we could do is rewrite the audio processing portion (25% of the overall codebase), and leave the gui (75%) as C++ for the time being.

**Comment by fanninpm** [comment]
> rewrite the audio processing portion (25% of the overall codebase)

[Symphonia](https://github.com/pdeljanov/Symphonia) could be a viable alternative for ffmpeg.

**Comment by expnkx** [comment]
fuck u riir losers. RRIV is the future. Rewrite Rust in V

**Comment by IThinkImOKAY** [comment]
this dude really suggested rust 🤣👍

**Comment by williamclarkmcbride** [comment]
> this dude really suggested rust 🤣👍

Better than Node I guess?

**Comment by meguminloli** [comment]
There is ffmpeg crate. But anyway looks like rewriting it isn't the smartest choice now.

**Comment by binex-dsk** [comment]
> > this dude really suggested rust 🤣👍
> 
> Better than Node I guess?

I think it's worse than Node. We need a JS rewrite immediately!

**Comment by IThinkImOKAY** [comment]
you got the whole squad laughing homie
