### ISSUE TITLE
Host an arch package repository..

### ISSUE THREAD

**Issue by georgebushfourtwenty** [Sneeds-Feed-and-Seed/sneedacity#60]
..and I'll add it to my based pacman.conf.

**Comment by formerlychuck** [comment]
I think once we have binaries we can try getting back into the AUR as well as a new package, maybe now that we have more steam they will see this isn't some "raid"

**Comment by T0x1cL** [comment]
> I think once we have binaries we can try getting back into the AUR as well as a new package, maybe now that we have more steam they will see this isn't some "raid"

I have this repo where I built a binary by modifying the audacity-git pkgbuild. I'm not sure whether or not that's acceptable in the archlinux community though. (The binary is outdated by a bunch of commits.)
https://github.com/T0x1cL/toxl-repo

**Comment by georgebushfourtwenty** [comment]
@T0x1cL, I doubt github does well with large files, maybe it is better to host the repository on something like netlify instead. It's a simple drag and drop. You can even have an index landing page.

**Comment by T0x1cL** [comment]
> @T0x1cL, I doubt github does well with large files, maybe it is better to host the repository on something like netlify instead. It's a simple drag and drop (or point netlify to your github repo). You can even have an index landing page.

Checked netlify out. ~~I have no idea how to do any webdev shit. I literally know nothing.~~ Pointed it to the gh repo, and ended up with a 404. (Directly linking to a file allows me to download it still.) I'm gonna try to hack something together using pure html because that's pretty much all I've learned in school, and I've also forgot it all. ~~I'll just look at someone else's work.~~

https://toxl-repo.netlify.app/

**Comment by thenexxuz** [comment]
I added to the AUR https://aur.archlinux.org/packages/sneedacity/ https://github.com/thenexxuz/sneedacity-aur

**Comment by T0x1cL** [comment]
> I added to the AUR https://aur.archlinux.org/packages/sneedacity/ https://github.com/thenexxuz/sneedacity-aur

The AUR returns 404

**Comment by thenexxuz** [comment]
Jannies deleted it..... :frowning_face:

**Comment by chuck-sneed** [comment]
https://github.com/Sneeds-Feed-and-Seed/sneedacity/issues/41#issuecomment-877631366

I suggest OBS ^ it includes an arch repo so all the work is done for you once you get the builds going

**Comment by mariaWitch** [comment]
Update on this.
We are now hosting an Arch repository here: https://repo.swurl.xyz/sneed/arch/x86_64

**Comment by jo620kix** [comment]
Although this package was back on AUR for some time, it is once again taken down by another TU (trusted user) `@Foxboron`.

This package was taken down 3 times:
* 1st time: Name is "offensive", "part of brigading campaign"
* 2nd time: Technical reasons
* 3rd time: "See previous requests."

Reference:
https://lists.archlinux.org/pipermail/aur-requests/2021-July/thread.html

**Comment by mariaWitch** [comment]
We have added a dedicated Arch repository for sneedacity.
Please see the updated readme.
