### ISSUE TITLE
The sign is a subtle joke.

### ISSUE THREAD

**Issue by atlcell** [Sneeds-Feed-and-Seed/sneedacity#61]
The sign is a subtle joke. The shop is called "Sneed's Feed & Seed", where feed and seed both end in the sound "-eed", thus rhyming with the name of the owner, Sneed. The sign says that the shop was "Formerly Chuck's", implying that the two words beginning with "F" and "S" would have ended with "-uck", rhyming with "Chuck". So, when Chuck owned the shop, it would have been called "Chuck's Fuck and Suck".

**Comment by nek0bit** [comment]
The sign is a subtle joke. The shop is called "Sneed's Feed & Seed", where feed and seed both end in the sound "-eed", thus rhyming with the name of the owner, Sneed. The sign says that the shop was "Formerly Chuck's," therefore, if we change "Sneed" to "Chuck", we get "Chuck's Feed and Seed".

**Comment by differentprogramming** [comment]
@atlcell why do you have to make me cry?

**Comment by mvasilkov** [comment]
I think the sign is a subtle joke you guys

**Comment by notevenaperson** [comment]
What sneed means??

**Comment by jstat17** [comment]
The joke is that Chuck used to own the shop, so it was called Chuck's Feed and Seed

**Comment by Xenoxide** [comment]
The sign is a subtle joke. The shop is called "Chuck's Fuck & Suck", where fuck and suck both end in the sound "-uck", thus rhyming with the name of the owner, Chuck. The sign says that the shop was "Formerly Sneed's", implying that the two words beginning with "F" and "S" would have ended with "-eed", rhyming with "Sneed". So, when Sneed owned the shop, it would have been called "Sneed's Feed and Seed"

**Comment by sneedfVg** [comment]
how about niggeracity

**Comment by atlcell** [comment]
> how about niggeracity

kys

**Comment by devenblake** [comment]
The sneed is a subtle chuck. The shop is called "Sign's Wine and Dine", where wine and dine both end in the sound "-ine", thus rhyming with the name of the owner, Sign. The sign says that the shop was "Formerly Joke's", implying that the two words beginning with "W" and "D" would have ended with "-oke", rhyming with "Joke". So, when Joke owned the shop, it would have been called "Joke's Woke and Doke"

**Comment by fort-ified** [comment]
the sneed is a subtwe chuck. ^^;; the s-shop is cawwed "sign's w-wine and d-dine", >_< whewe wine a-and dine both e-end in the sound "-ine", mya t-thus whyming w-with the name o-of the ownew, mya sign. the sign says that the shop was "fowmewwy joke's",  impwying t-that the two wowds beginning with "w" and "d" w-wouwd have ended with "-oke", XD w-whyming with "joke". :3 so, when joke owned the shop, it wouwd have b-been cawwed "joke's woke and doke"

**Comment by natewrench** [comment]
> The sneed is a subtle chuck. The shop is called "Sign's Wine and Dine", where wine and dine both end in the sound "-ine", thus rhyming with the name of the owner, Sign. The sign says that the shop was "Formerly Joke's", implying that the two words beginning with "W" and "D" would have ended with "-oke", rhyming with "Joke". So, when Joke owned the shop, it would have been called "Joke's Woke and Doke"

Sine's wine and brine formerly joke because joke went woke and broke
