### ISSUE TITLE
Is this a meme?

### ISSUE THREAD

**Issue by kuator** [Sneeds-Feed-and-Seed/sneedacity#65]
Is this a meme project or I can actually use it for my work?

**Comment by denimchewer56** [comment]
A little bit of both.

**Comment by ChucksConsulting** [comment]
> Is this a meme project or I can actually use for my work?

It's an alpha.

**Comment by PlavorSeol** [comment]
I think both.
The name (or maybe, overall branding) of this project is indeed a *reference* of a meme, but it does not mean this project is not suitable for actual use.
As far as I see, *botnet* (telemetry) removal has happened, and actual development is going to happen as well.
One can *name* a project with a reference to a meme and start working on it. Why not? It is funny, but the project does the job well.

**Comment by georgebushfourtwenty** [comment]
Sometimes an internet meme is a solution to a problem you are facing.

This meme did a good job at bringing people together in this age of turmoil.

**Comment by magnus-ISU** [comment]
At present it is up to date with audacity. It seems there is some interest in it so it is possible it will continue to be updated and gain more features.

**Comment by woodenphone** [comment]
I hope you madlads keep on working to make a viable competitor.

**Comment by meguminloli** [comment]
Looks like it got XDG directories and other features. Also we repaired plugins. It's alpha quality, so don't expert stability for some time. We need to settle the project now.
