### ISSUE TITLE
Add support for fancy german cars

### ISSUE THREAD

**Issue by nukeop** [Sneeds-Feed-and-Seed/sneedacity#68]
**Is your feature request related to a problem? Please describe.**
The program refuses to run and returns a `c1ty-5l1ck3r` error.

**Describe the solution you'd like**
Sneedacity should recognize cars made in Guatemala.

**Describe alternatives you've considered**
Gucci loafers

**Additional context**
I'm sorry, I believe in good grooming.

**Comment by kakolisgay** [comment]
> The program refuses to run and returns a `c1ty-5l1ck3r` error.

Not a bug.

**Comment by gamelone** [comment]
> The program refuses to run and returns a `c1ty-5l1ck3r` error.

This error is given if running with a soil-lib of 9.6 or higher, the highest supported soil-lib is 8, consider reverting

**Comment by formerlychuck** [comment]
WELL LA DEE DA

**Comment by sonsofsneed3** [comment]
sneed
