### ISSUE TITLE
Libera.Chat project registration

### ISSUE THREAD

**Issue by jobbautista9** [Sneeds-Feed-and-Seed/sneedacity#71]
Since the #sneedacity channel on libera is pretty much "official" right now, should we do a project registration? The procedure is here: https://libera.chat/chanreg

As a registered project in Libera we get to have project cloaks and reserve the #sneedacity-* namespace. This also can make our project look more legitimate and not merely as yet another creation from /g/. (And I'm not even from /g/!)

If we go through this, there's a chance that Libera staff might just reject our request, considering the origins of the project. But I think I can be able to convince them to reg us, as I'm an established user on old freenode for years.

**Comment by meguminloli** [comment]
Maybe we should wait some time to see if the project isn't removed from Github by the orange and the red sites.

**Comment by tengkuizdihar** [comment]
Maybe you should use matrix instead? Why IRC when matrix exist?

**Comment by jobbautista9** [comment]
Because not everyone wants to use matrix, like me. None of the clients offered by matrix suit my taste. We can always bridge the matrix room to the IRC channel, I don't think there's harm for the matrix people in bridging. In fact if we bridge the matrix room to IRC channel right now, I would have to devote more time in making sure the channel doesn't get nuked by Libera staff. Perhaps a channel in Rizon would be better for bridging instead?

**Comment by binex-dsk** [comment]
we could also use XMPP since it's not centralized, already made a room `sneedacity@rooms.swurl.xyz`

**Comment by jobbautista9** [comment]
It's almost been a week now, and so far we haven't had any major problems in Libera. Do you want me to PM one of the Projects & Community Team and see if we are likely to be considered eligible for registration?

**Comment by mariaWitch** [comment]
There isn't anything to me which would suggest that we shouldn't, especially since we are still here after all this time.
But I will wait for further input on this matter.

**Comment by ChucksConsulting** [comment]
I don't think there is going to be enough interest to have an active IRC channel. Closing this unless somebody still uses the IRC channel.
