### ISSUE TITLE
MTF they/them seeking validation

### ISSUE THREAD

**Issue by MrGucciL** [Sneeds-Feed-and-Seed/sneedacity#72]
The other audacity forks are continually harassing and committing violence against me for being transgender and I just don't know what to do. Will sneedacity have  more welcoming community for the LGBTSNEED++ community?

**Comment by meguminloli** [comment]
Sir, please delete this now.

**Comment by mvasilkov** [comment]
Madam*

**Comment by minexew** [comment]
Blasphemy!

**Comment by Genghius** [comment]
> The other audacity forks are continually harassing and committing violence against me for being transgender and I just don't know what to do. Will sneedacity have more welcoming community for the LGBTSNEED++ community?

We are welcoming to anyone and everyone that sneeds a spyware-free version of audacity.
