### ISSUE TITLE
On first startup, the "Check Online" link links to a broken URL that appears to be an audacity.org link that has been sed-replaced with sneedacity.org

### ISSUE THREAD

**Issue by magnus-ISU** [Sneeds-Feed-and-Seed/sneedacity#73]
**Describe the bug**
`Check Online` button links to https://www.sneedacityteam.org/download/?from_ver=3.0.4-alpha-20210707 which is a broken link. Probably due to a general patch to change all occurences of audacity to sneedacity.

**To Reproduce**
1. Build sneedacity
2. Click on Check Online
3. Web browser opens to broken url

**Expected behavior**
Links to this github repository or maybe another place where you can download precompiled binaries for different platforms (saw on 4chan some people had bought domain names so maybe possible?)

**Screenshots**
![image](https://user-images.githubusercontent.com/75949275/124732627-e6cc2800-df02-11eb-9019-24e7729fb2b3.png)

**Additional information (please complete the following information):**
 - OS: Arch Linux (built with the provided PKGBUILD)
 - Version 3.0.4-alpha-20210707

**Comment by Ckath** [comment]
theres quite a lot, pretty much the entirety of HelpText.cpp got sneeded like this. should they just be returned to the old audacity links for manuals and just link to https://github.com/Sneeds-Feed-and-Seed/sneedacity otherwise?

at least until either the releases are worked out or someone makes some sneedacity landing page

**Comment by jobbautista9** [comment]
Maybe we can import the whole wiki of https://alphamanual.audacityteam.org to the InstallGentoo Wiki?

**Comment by Ckath** [comment]
certainly one way to do it, would require a lot of effort though redoing the pictures and such if you want to go all the way. if anyones up for it might be the best option for sneedware

**Comment by meguminloli** [comment]
We can copy the files if we have access to the server.

**Comment by Furitenman** [comment]
In `src/HelpText.cpp`:
```
// Url with Version check args attached.
const URLString VerCheckUrl()
{
   //The version we intend to use for live Sneedacity.
#define VER_CHECK_URL "https://www.sneedacityteam.org/download/?"
//For testing of our scriptlet.
//#define VER_CHECK_URL "http://www.sneedacityteam.org/slug/?"
//For testing locally
//#define VER_CHECK_URL "http://localhost:63342/WorkingDocs/demos/download.html?"

   return wxString( wxT(VER_CHECK_URL)) +VerCheckArgs();
}
```
This is the line they use. Maybe we can hardcode it to the repo for the time being?

**Comment by Ckath** [comment]
thats fine since no one is picking this up yet, can always change it again later. note also the majority of those links are broken in HelpText.cpp, if those are also fixed to where it makes sense to installgentoo wiki/audacity/this repo it'd be swell.

**Comment by Furitenman** [comment]
> 
> 
> thats fine since no one is picking this up yet, can always change it again later. note also the majority of those links are broken in HelpText.cpp, if those are also fixed to where it makes sense to installgentoo wiki/audacity/this repo it'd be swell.
>
I'm fixing them as we speak. I'll hardcode it for now. I'll leave a comment as well so someone can find it and fix it later.
