### ISSUE TITLE
Sneedacity crashes on startup

### ISSUE THREAD

**Issue by ryusuke-okuno** [Sneeds-Feed-and-Seed/sneedacity#75]
Sneedacity crashes on startup, assertion error in getPlayDevIndex()

```
ASSERT INFO:
/home/phi/source/sneedacity/src/AudioIOBase.cpp(643): assert "false" failed in getPlayDevIndex().

BACKTRACE:
[1] AudioIOBase::getPlayDevIndex(wxString const&)
[2] AudioIOBase::HandleDeviceChange()
[3] AudioIO::AudioIO()
[4] AudioIO::Init()
[5] SneedacityApp::InitPart2()
[6] SneedacityApp::OnInit()
[7] wxAppConsoleBase::CallOnInit()
[8] wxEntry(int&, wchar_t**)
[9] wxEntry(int&, char**)
[10] main
[11] __libc_start_main
[12] _start
```

**Additional information**
 - OS: Ubuntu 20.04 LTS
 - Pulseaudio

**Screenshot**
![Screenshot from 2021-07-07 11-27-58](https://user-images.githubusercontent.com/82731346/124736883-b9d64000-df17-11eb-920f-69de42931321.png)

**Comment by Ckath** [comment]
cant reproduce this just compiling from master, what build are you using? is it just the latest ubuntu build from https://github.com/Sneeds-Feed-and-Seed/sneedacity/actions/runs/1007342505?

looking at the code all I can see causing it is you not having a default pulseaudio device set:
https://github.com/Sneeds-Feed-and-Seed/sneedacity/blob/b50b46ee02854ad21977ce8f99fb59c70cb7175f/src/AudioIOBase.cpp#L633-L645

either that or something is borked in pulseaudio handling/setup which causes it to fail getting it, at least for your system

**Comment by kakolisgay** [comment]
*Seems* to be an environment issue, what does `Settings -> Sounds` look like?

**Comment by rndtrash** [comment]
+1, assert window appears for me on Xubuntu 21.04
![Снимок экрана_2021-07-07_13-11-58](https://user-images.githubusercontent.com/6745157/124741980-f197b480-df24-11eb-99da-d982549e97aa.png)

**Comment by Ckath** [comment]
> +1, assert window appears for me on Xubuntu 21.04
> ![Снимок экрана_2021-07-07_13-11-58](https://user-images.githubusercontent.com/6745157/124741980-f197b480-df24-11eb-99da-d982549e97aa.png)

>Using: PortAudio

think its related to this, were you also using PortAudio OP?
see my previous code reference where it explicitely mentions a weird clause where portaudio returns the wrong thing sometimes, which is when it lands in the assert error you posted about.

I can just quickly fish out the `wxASSERT(false)` thing which deliberately crashes it on this case in which case sneedacity will attempt to keep going with deviceNum = 0 but I'm not sure what effects that will have for you

**Comment by ryusuke-okuno** [comment]
My sound settings look like this:
![Screenshot from 2021-07-07 12-16-08](https://user-images.githubusercontent.com/82731346/124742683-3f102380-df1d-11eb-9411-6bce6c17036a.png)

And I built sneedacity from source, with the instructions given in https://github.com/Sneeds-Feed-and-Seed/sneedacity/blob/master/BUILDING.md

**Comment by ryusuke-okuno** [comment]
I tried to remove the assertion in `AudioIOBase`, and I get a different assertion error this time.

ASSERT INFO:
/home/phi/source/sneedacity/src/AudioIOBase.cpp(700): assert "false" failed in getRecordDevIndex().

BACKTRACE:
[1] AudioIOBase::getRecordDevIndex(wxString const&)
[2] AudioIOBase::HandleDeviceChange()
[3] AudioIO::AudioIO()
[4] AudioIO::Init()
[5] SneedacityApp::InitPart2()
[6] SneedacityApp::OnInit()
[7] wxAppConsoleBase::CallOnInit()
[8] wxEntry(int&, wchar_t**)
[9] wxEntry(int&, char**)
[10] main
[11] __libc_start_main
[12] _start

**Comment by meguminloli** [comment]
Can you try out the latest build from artifacts?

**Comment by Ckath** [comment]
> I tried to remove the assertion in `AudioIOBase`, and I get a different assertion error this time.
> 
> ASSERT INFO:
> /home/phi/source/sneedacity/src/AudioIOBase.cpp(700): assert "false" failed in getRecordDevIndex().
> 
> BACKTRACE:
> [1] AudioIOBase::getRecordDevIndex(wxString const&)
> [2] AudioIOBase::HandleDeviceChange()
> [3] AudioIO::AudioIO()
> [4] AudioIO::Init()
> [5] SneedacityApp::InitPart2()
> [6] SneedacityApp::OnInit()
> [7] wxAppConsoleBase::CallOnInit()
> [8] wxEntry(int&, wchar_t**)
> [9] wxEntry(int&, char**)
> [10] main
> [11] __libc_start_main
> [12] _start

okay so both `Pa_GetDefaultInputDevice` and `Pa_GetDefaultOutputDevice` return something < 0 for some reason on your PortAudio systems. and audacity upstream has guarded this weird error with the asserts and comments about `TODO: Look into this a bit more`.

you could fish out the `wxASSERT(false)` there too in a final attempt (last one in the file like that), but this might be something that we'll just have to wait on, or maybe even something wrong in portaudio

**Comment by rndtrash** [comment]
OK, I've downloaded the libpulse-dev library, removed CMakeCache, reconfigured and rebuilt it from scratch, and it works!
![Снимок экрана_2021-07-07_13-25-56](https://user-images.githubusercontent.com/6745157/124743942-e8a7e280-df26-11eb-854b-63a1068ebac6.png)
(looks ugly with dark theme tho, lol!)
But, there are lots of exceptions in the console, which do not affect the sound playback.
```
Expression 'ret' failed in '/home/-/build/sneedacity/lib-src/portaudio-v19/src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in '/home/-/build/sneedacity/lib-src/portaudio-v19/src/hostapi/alsa/pa_linux_alsa.c', line: 1904
Expression 'PaAlsaStreamComponent_Initialize( &self->capture, alsaApi, inParams, StreamDirection_In, NULL != callback )' failed in '/home/-/build/sneedacity/lib-src/portaudio-v19/src/hostapi/alsa/pa_linux_alsa.c', line: 2171
Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in '/home/-/build/sneedacity/lib-src/portaudio-v19/src/hostapi/alsa/pa_linux_alsa.c', line: 2839
13:24:44: Debug: PortAudio stream error creating device list: ALSA:HDA Intel PCH: ALC298 Analog (hw:0,0): Device unavailable
```

**Comment by meguminloli** [comment]
Can you try the binary from https://github.com/Sneeds-Feed-and-Seed/sneedacity/actions/runs/1007567058 ?
I would like to find out if it's a problem related to some library that changed API.

**Comment by Ckath** [comment]
> But, there are lots of exceptions in the console, which do not affect the sound playback.
> 
> ```
> Expression 'ret' failed in '/home/-/build/sneedacity/lib-src/portaudio-v19/src/hostapi/alsa/pa_linux_alsa.c', line: 1736
> Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in '/home/-/build/sneedacity/lib-src/portaudio-v19/src/hostapi/alsa/pa_linux_alsa.c', line: 1904
> Expression 'PaAlsaStreamComponent_Initialize( &self->capture, alsaApi, inParams, StreamDirection_In, NULL != callback )' failed in '/home/-/build/sneedacity/lib-src/portaudio-v19/src/hostapi/alsa/pa_linux_alsa.c', line: 2171
> Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in '/home/-/build/sneedacity/lib-src/portaudio-v19/src/hostapi/alsa/pa_linux_alsa.c', line: 2839
> 13:24:44: Debug: PortAudio stream error creating device list: ALSA:HDA Intel PCH: ALC298 Analog (hw:0,0): Device unavailable
> ```
I've been getting tons of those since the beginning even before all the changes so I'm assuming the warnings are ignorable if things work still. so where does this leave the issue now.. is your solution good enough to leave it as a 'known solved issue' to reference people if they bring it up again? 

also does upstream audacity work with your system or does it also fail on the same?

**Comment by Ckath** [comment]
just also spotted 
```      
// JKC: This ASSERT will happen if you run with no config file
// This happens once.  Config file will exist on the next run.
```

but I guess that was the case for you, it could still be a rename related issue somewhere, though configs are created correctly from what I can see for everything else

**Comment by meguminloli** [comment]
> just also spotted
> 
> ```
> // JKC: This ASSERT will happen if you run with no config file
> // This happens once.  Config file will exist on the next run.
> ```
> 
> but I guess that was the case for you, it could still be a rename related issue somewhere, though configs are created correctly from what I can see for everything else

Imagine the dev that came with the idea to assert the program instead of restarting it.

**Comment by Ckath** [comment]
> > just also spotted
> > ```
> > // JKC: This ASSERT will happen if you run with no config file
> > // This happens once.  Config file will exist on the next run.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but I guess that was the case for you, it could still be a rename related issue somewhere, though configs are created correctly from what I can see for everything else
> 
> Imagine the dev that came with the idea to assert the program instead of restarting it.

the more I look at the code the more I see the `// what is this doing here` `// should not happen` `will be fine next run` meme tier comments and bodges.
what a mess honestly

**Comment by ryusuke-okuno** [comment]
Okay, so I guess this was a build problem. The app Image works fine, and recompiling with libpulse-dev solved it.

**Comment by rndtrash** [comment]
> just also spotted
> 
> ```
> // JKC: This ASSERT will happen if you run with no config file
> // This happens once.  Config file will exist on the next run.
> ```
> 
> but I guess that was the case for you, it could still be a rename related issue somewhere, though configs are created correctly from what I can see for everything else

i swear this assert occured for me at least twice :D Where's sneedacity config is located at?

> also does upstream audacity(or some other fork), work with your system or does it also fail on the same?

tenacity builds and works without libpulse-dev. I don't even know anymore...

**Comment by Ckath** [comment]
> i swear this assert occured for me at least twice :D Where's sneedacity config is located at?
`~/.sneedacity-data` should have it I think

**Comment by rndtrash** [comment]
> > i swear this assert occured for me at least twice :D Where's sneedacity config is located at?
> 
> `~/.sneedacity-data` should have it I think

It builds and works without both pulse-dev and sneedacity-data (I should note that I don't have Audacity and its dependencies installed)
Dunno, maybe it's just a conan fuck-up?

**Comment by Ckath** [comment]
> It builds and works without both pulse-dev and sneedacity-data (I should note that I don't have Audacity and its dependencies installed)
> Dunno, maybe it's just a conan fuck-up?

no clue, the comments around the asserts make it sound like its some rare edgecase with portaudio. just a peek and its the AudioIOBase.cpp is still 1:1 with audacity upstream too so it cant be too bad of an issue.

for now just going to leave this closed and say its solved at that
