### ISSUE TITLE
mac_os build fails randomly

### ISSUE THREAD

**Issue by Ckath** [Sneeds-Feed-and-Seed/sneedacity#77]
**Describe the bug**
sometimes it does, like in #76 [here,](https://github.com/Sneeds-Feed-and-Seed/sneedacity/runs/3008355457) then waiting for it to recheck it [goes through](https://github.com/Sneeds-Feed-and-Seed/sneedacity/runs/3008128916), then on merge it fails again.

```
CPack Error: Error executing: /usr/bin/hdiutil detach "/Volumes/sneedacity-macos-3.0.4-alpha-20210707+181694a-Intel"
CPack Error: Error detaching temporary disk image.
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: Sneedacity
Error: Process completed with exit code 1.
```
not sure this is related to the ci config, it being macos or githubs horrible actions system

**Comment by meguminloli** [comment]
Are there any completely free CI actions to test against?

**Comment by Ckath** [comment]
discussing the option of sr.ht's CI as a possibl ereplacement, not sure how 1:1 it is or how much he'll enjoy it

**Comment by Ckath** [comment]
watch me rerun it again and it going through for no reason now

**Comment by kakolisgay** [comment]
We could just retry the build 3 times and then fail :^)

**Comment by Ckath** [comment]
> We could just retry the build 3 times and then fail :^)

\>ubuntu build ~15 minutes
\>macos builds >1hour
\>windows build ~30 mintues
sure

**Comment by kakolisgay** [comment]
The package task only takes a minute or less so we wouldn't be adding much to the already long build tasklist. The compile and build tasks run fine, it's just the package task that has this weird bug, so we *should* be able to just retry it.

**Comment by kakolisgay** [comment]
Not entirely sure how to get a task to repeat, docs don't seem to mention retrying tasks. Worst case we can just have the task script detect fuckups and clean up before reattempting

**Comment by meguminloli** [comment]
> discussing the option of sr.ht's CI as a possible replacement, not sure how 1:1 it is or how much he'll enjoy it

It's paid now. Is Gitlab CI free?

**Comment by kakolisgay** [comment]
Gitlab CI is free, but projects have a limit on ci minutes iirc

**Comment by Ckath** [comment]
>The package task only takes a minute or less so we wouldn't be adding much to the already long build tasklist.

ah yeah good point, might not be that bad.
also looking up the error it seems to be some specific macosism with the actions. related to that temp system. a weird workaround posted from another package, doesnt seem very automatic would still need to catch it failing first:
```
$ mv temp.dmg temp2.dmg
$ cp temp2.dmg temp.dmg
# redo hdiutil
$ /usr/bin/hdiutil convert "/Users/mathieu/Documents/workspace/rtabmap/build/_CPack_Packages/Darwin/DragNDrop/temp.dmg" -format UDZO -imagekey zlib-level=9 -o "/Users/mathieu/Documents/workspace/rtabmap/build/_CPack_Packages/Darwin/DragNDrop/RTABMap-0.17.3-Darwin/RTABMap-0.17.3-Darwin.dmg"
$ mv /Users/mathieu/Documents/workspace/rtabmap/build/_CPack_Packages/Darwin/DragNDrop/RTABMap-0.17.3-Darwin/RTABMap-0.17.3-Darwin.dmg .```

**Comment by meguminloli** [comment]
Remember anons, we don't want to spend a cent on this, because we have no funding.

**Comment by Ckath** [comment]
recreational sneeding while having to actually work for rent

**Comment by Ckath** [comment]
> Gitlab CI is free, but projects have a limit on ci minutes iirc. If we ran our own runner, that limit wouldn't apply though

from what I remember anything gitlab was always less restrictive than github in terms of freemium features, cant imagine they'd be worse with actions than github

**Comment by meguminloli** [comment]
I've never written a Gitlab CI file, maybe someone can help.

**Comment by Ckath** [comment]
I'm looking at their 'gitlab ci for github' thing but not entirely sure yet how I'd go about setting up a ci repo https://about.gitlab.com/solutions/github/

**Comment by meguminloli** [comment]
We have a Gitlab mirror so we can build there. It's not like we need to build for Github. Maybe check if builds are reproducable.

**Comment by Ckath** [comment]
that'd be fine too and probably less effort, as long as its verifyable somewhere it compiles without having to compile it

**Comment by devenblake** [comment]
Have you tried installing gentoo?

**Comment by Ckath** [comment]
it already kinda fixed itself so now I can continue never installing gentoo. but thanks for the concern.

closed until it becomes an issue again
