### ISSUE TITLE
Compilation fails on cairo.h not found

### ISSUE THREAD

**Issue by ghost** [Sneeds-Feed-and-Seed/sneedacity#85]
# **Describe the bug**

Cloned the repo and tried to compile it as mentioned on #78
Returns with file cairo.h not found. (I've installed the cairo package)
```
FAILED: source_subfolder/libs/core/CMakeFiles/core.dir/__/__/__/__/src/common/cairo.cpp.o 
/gnu/store/9jkrwb0b4nv3za898siggc002xy4vh55-profile/bin/c++  -DDLL_EXPORTS -DWXBUILDING -DWXMAKINGDLL_CORE -DWXUSINGDLL -DWX_PRECOMP -D_GLIBCXX_USE_CXX11_ABI=1 -D_LIB -D_UNICODE -D__WXGTK2__ -D__WXGTK__ -Dcore_EXPORTS -DwxUSE_BASE=0 -DwxUSE_GUI=1 -I/home/anon/.conan/data/libpng/1.6.37/_/_/package/61378f3db01d0a2424aa7ca62df88dcbfa0c279e/include -I/home/anon/.conan/data/libjpeg-turbo/2.0.5/_/_/package/10124878f77fe964cc9acc46bfaa384dae0053a1/include -Ilib/wx/include/gtk2-unicode-3.1 -I../source_subfolder/include -I/home/anon/.conan/data/expat/2.2.9/audacity/stable/package/46863e2dc48a06454dddba7dea457fd3976ba047/include -isystem /home/anon/.conan/data/zlib/1.2.11/_/_/package/46863e2dc48a06454dddba7dea457fd3976ba047/include -m64 -g  -fPIC   -pthread -std=gnu++14  -Winvalid-pch -include "/home/anon/.conan/data/wxwidgets/3.1.3.1-audacity/_/_/build/30cf406d6ca56e351d0981b27cd1fe83fcb3a119/build_subfolder/source_subfolder/libs/core/cotire/core_CXX_prefix.hxx" -MD -MT source_subfolder/libs/core/CMakeFiles/core.dir/__/__/__/__/src/common/cairo.cpp.o -MF source_subfolder/libs/core/CMakeFiles/core.dir/__/__/__/__/src/common/cairo.cpp.o.d -o source_subfolder/libs/core/CMakeFiles/core.dir/__/__/__/__/src/common/cairo.cpp.o -c ../source_subfolder/src/common/cairo.cpp
../source_subfolder/src/common/cairo.cpp:24:10: fatal error: cairo.h: No such file or directory
 #include <cairo.h>
          ^~~~~~~~~
compilation terminated.
[161/596] Building CXX object source_subfolder/libs/core/CMakeFiles/core.dir/__/__/__/__/src/common/bookctrl.cpp.o
[162/596] Building CXX object source_subfolder/libs/core/CMakeFiles/core.dir/__/__/__/__/src/common/checkboxcmn.cpp.o
[163/596] Building CXX object source_subfolder/libs/core/CMakeFiles/core.dir/__/__/__/__/src/common/btncmn.cpp.o
ninja: build stopped: subcommand failed.
wxwidgets/3.1.3.1-audacity: 
WARN: wxwidgets/3.1.3.1-audacity: requirement expat/2.2.9 overridden by your conanfile to expat/2.2.9@audacity/stable 
wxwidgets/3.1.3.1-audacity: WARN: Package binary is corrupted, removing: 30cf406d6ca56e351d0981b27cd1fe83fcb3a119
wxwidgets/3.1.3.1-audacity: WARN: Build folder is dirty, removing it: /home/anon/.conan/data/wxwidgets/3.1.3.1-audacity/_/_/build/30cf406d6ca56e351d0981b27cd1fe83fcb3a119
wxwidgets/3.1.3.1-audacity: ERROR: Package '30cf406d6ca56e351d0981b27cd1fe83fcb3a119' build failed
wxwidgets/3.1.3.1-audacity: WARN: Build folder /home/anon/.conan/data/wxwidgets/3.1.3.1-audacity/_/_/build/30cf406d6ca56e351d0981b27cd1fe83fcb3a119
ERROR: wxwidgets/3.1.3.1-audacity: Error in build() method, line 256
        cmake.build()
        ConanException: Error 1 while executing cmake --build '/home/anon/.conan/data/wxwidgets/3.1.3.1-audacity/_/_/build/30cf406d6ca56e351d0981b27cd1fe83fcb3a119/build_subfolder' '--' '-j4'
CMake Error at cmake-proxies/cmake-modules/conan.cmake:631 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake-proxies/cmake-modules/SneedacityDependencies.cmake:233 (conan_cmake_install)
  cmake-proxies/cmake-modules/SneedacityDependencies.cmake:254 (_conan_install)
  CMakeLists.txt:480 (resolve_conan_dependencies)


-- Configuring incomplete, errors occurred!
See also "/tmp/sneed_build/CMakeFiles/CMakeOutput.log".
See also "/tmp/sneed_build/CMakeFiles/CMakeError.log".
```

# **To Reproduce**
```
git clone https://github.com/Sneeds-Feed-and-Seed/sneedacity
mkdir sneed_build
cd sneed_build
cmake -G "Unix Makefiles" -Dsneedacity_use_ffmpeg=loaded ../sneedacity
```
5. See error

## **Expected behavior**
Package compiles successfully

## **Additional information:**
 - OS: GNU GuixSD
 - Version: Sneedacity master

**Comment by meguminloli** [comment]
Looks like Guix has two cairo packages, [cairo](http://guix.gnu.org/en/packages/cairo-1.16.0/) and [cairo-xcb](http://guix.gnu.org/en/packages/cairo-xcb-1.16.0/). Which one of those are you using?
## Disclaimer
I'm not a Guix user.

**Comment by hey-ram** [comment]
Tried compiling with either of both the packages installed and I still see the same error.

**Comment by meguminloli** [comment]
Can someone on Nix try to compile this? This might be related to how Nix and Guix handle the filesystem.

**Comment by Ckath** [comment]
it could be named differently or be in some subdir, is there a guix development audacity package to peek at?

**Comment by meguminloli** [comment]
https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/audio.scm#n690
From 685 to 797.

**Comment by Ckath** [comment]
so they mention some `audacity-add-include.patch` and `audacity-build-with-system-portaudio.patch` there, which probably holds the key to this, if I can find where they are. weird things if from what I can understand of that audacity package it doesnt seem to dep cairo even.

**Comment by meguminloli** [comment]
> so they mention some `audacity-add-include.patch` and `audacity-build-with-system-portaudio.patch` there, the former of which probably holds the key to this not working as is. if I can find where they are. weird things if from what I can understand of that audacity package it doesnt seem to dep cairo even.

https://guix.gnu.org/en/packages/audacity-2.4.2/

**Comment by Ckath** [comment]
I'm not convinced anymore, the one that I thought would magically solve it is just:
```diff
Without <sys/time.h>, gettimeofday is undefined.

diff --git a/src/AudioIO.cpp b/src/AudioIO.cpp
index 0187e3962..e15d55f4c 100644
--- a/src/AudioIO.cpp
+++ b/src/AudioIO.cpp
@@ -479,6 +479,8 @@ time warp info and AudioIOListener and whether the playback is looped.
 #include "../lib-src/portmidi/porttime/porttime.h"
 #include "../lib-src/header-substitutes/allegro.h"
 
+#include <sys/time.h>
+
    #define MIDI_SLEEP 10 /* milliseconds */
    // how long do we think the thread that fills MIDI buffers,
    // if it is separate from the portaudio thread,
```
the other one is portaudio specific

**Comment by Ckath** [comment]
it is 2.4.2 though, what are the chances they broke it on guix in all those versions past 2.4.2?
I'll have a look at the 2.4.2 source and see if cairo is even there at that time. 

one last thing you can try @hey-ram I also see some mentions of package depping `cairomm`, that may or may not help compiling for now

**Comment by meguminloli** [comment]
I found this patch also on Gentoo's ebuild. I'm not sure if it applies to 3.0.x builds. All distros stopped updating Audacity from 2.6.x.

**Comment by Ckath** [comment]
okay this doesnt help, both times the only place that `#include <cairo.h>` even gets mentioned is
```
lib-src/lv2/lv2/plugins/eg-sampler.lv2/sampler_ui.c:32:#include <cairo.h>
lib-src/lv2/lv2/plugins/eg-scope.lv2/examploscope_ui.c:26:#include <cairo.h>
``` exactly the same for latest sneedacity and audacity 2.4.2

**Comment by meguminloli** [comment]
Looks like the problem is related to compiling wxWidgets. wxWidgets depends on GTK2 and probably uses Cairo surfaces. Maybe we should move wxWidgets to GTK3.

**Comment by Ckath** [comment]
ah so its finally running into the wxWidgets packaging pain

**Comment by meguminloli** [comment]
Can you try to compile a simple C program like
```
#include <cairo.h>

int main() {}
```
with clang `pkg-config --libs --cflags gtkmm-3.0 cairomm-1.0` -O3 main.c -o main
Maybe it's an environment issue

**Comment by hey-ram** [comment]
Yeah, so it might be a fault on my side, running the trivial program above fails with the same error. Any idea how to fix it?

**Comment by Ckath** [comment]
not sure if anyone is familiar with guix within this org, I'm not at any rate. but assuming you tried the before mentioned `cairomm` package too, no clue. will have to bother some guix people somewhere to find out whats going on.

**Comment by ChucksConsulting** [comment]
Compiling on Guix is not supported.
