### ISSUE TITLE
Long build times in GH actions

### ISSUE THREAD

**Issue by brmonaghan** [Sneeds-Feed-and-Seed/sneedacity#89]
![long build times](https://user-images.githubusercontent.com/71337477/124825977-4c8bd480-df42-11eb-8a82-0303ef56f13a.png)
There is a VERY long build times of ALMOST 20 MINUTES as of this writing!

**Comment by kakolisgay** [comment]
This seems to be a problem inherited from upstream, running the builds on a more powerful runner could help

**Comment by brmonaghan** [comment]
Ok thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Furitenman** [comment]
I'm ignorant on this github actions but, will we have to pay to get a faster compilation time?

**Comment by mariaWitch** [comment]
Mostly solved with the move to ninja from make. ccache will completely fix the issue.

Closed as this has been addressed

**Comment by brmonaghan** [comment]
Thank you so much!
@mariaWitch will this need a change in building the code?

**Comment by mariaWitch** [comment]
For faster builds, follow the ninja build instructions on the  how to build issue
