### ISSUE TITLE
Mirrors

### ISSUE THREAD

**Issue by eylles** [Sneeds-Feed-and-Seed/sneedacity#95]
The list of sneedacity mirrors:
https://gitlab.com/sneeds-feed-and-seed/sneedacity
https://codeberg.org/Sneeds-Feed-and-Seed/sneedacity
https://git.funny.cl/Sneeds-Feed-and-Seed/sneedacity

Please post the links to other mirrors.

**Comment by Ckath** [comment]
theres more?

**Comment by meguminloli** [comment]
The last link doesn't even work. Also it would be better to put it in README.

**Comment by meguminloli** [comment]
I pinned it however.

**Comment by eylles** [comment]
Welp, the annon who contributed the last link apparently doesn't have enough bandwith on his VPS to handle all the traffick.

**Comment by Ckath** [comment]
> Welp, the annon who contributed the last link apparently doesn't have enough bandwith on his VPS to handle all the traffick.

what traffic

**Comment by eylles** [comment]
The sneedflux of visits since he shared that link on a sneedacity thread.

**Comment by Ckath** [comment]
a moment of silence for the sneeded

**Comment by binex-dsk** [comment]
> Welp, the annon who contributed the last link apparently doesn't have enough bandwith on his VPS to handle all the traffick.

not even using a VPS, just a 2011 dell laptop lel

the thing is it got flooded so badly that I had to force stop the gitea service, when i start it every other process on the machine pretty much just freezes, and after a certain point i can't even input anything physically

I'll see if i can maybe fix that but anyways, my funny has moved to https://git.swurl.xyz/swirl/ebuilds. will probably try and start gitea once i finish setting up some other stuff

**Comment by eylles** [comment]
@binex-dsk good gateway dude.

**Comment by binex-dsk** [comment]
OK I FIXED THE PROBLEM, MATRIX WAS JUST BEING EXTREMELY FUNNY AND PLAYING EXTREMELY WELL WITH GITEA.

THE NEW MIRROR AT https://git.swurl.xyz/Sneeds-Feed-and-Seed/sneedacity IS UP

**Comment by vixfwis** [comment]
http://bs5sdmtmhoub3k7u7dsvgn3ctz4mgypubj6tqywbjemxtqvbk2qyqbad.onion/Sneeds-Feed-and-Seed/sneedacity

**Comment by binex-dsk** [comment]
nice ip grabber

mine has an onion mirror as well: https://git.z6d5jm2owmfzf67e5ow77rqvutf2rfclur353w5v4sni4frbx7asqdid.onion/Sneeds-Feed-and-Seed/sneedacity

**Comment by vixfwis** [comment]
> nice ip grabber

what? tor site is an ip grabber?

**Comment by binex-dsk** [comment]
sorry i accidentally used DEA lingo outside of DEA

basically it means suspicious or untrustworthy link

**Comment by eylles** [comment]
>ip grabbing being useful
kek unless you have an enterprise plan your isp shares your ip with a crapton of users, can't track u for shit with ipv4 nowadays

**Comment by mariaWitch** [comment]
The list of sneedacity mirrors:
https://gitlab.com/sneeds-feed-and-seed/sneedacity
https://codeberg.org/Sneeds-Feed-and-Seed/sneedacity
https://git.swurl.xyz/Sneeds-Feed-and-Seed/sneedacity
https://git.z6d5jm2owmfzf67e5ow77rqvutf2rfclur353w5v4sni4frbx7asqdid.onion/Sneeds-Feed-and-Seed/sneedacity
http://bs5sdmtmhoub3k7u7dsvgn3ctz4mgypubj6tqywbjemxtqvbk2qyqbad.onion/Sneeds-Feed-and-Seed/sneedacity

(Placing them into one post for safe keeping.)

**Comment by vixfwis** [comment]
I finally fixed my nginx config, so there's one more (sort of, same server onion site)
https://git.vixfwis.dev/Sneeds-Feed-and-Seed/sneedacity

**Comment by Ckath** [comment]
list was finally added to readme, open another issue or pr if theres ever a need for one to be added

**Comment by binex-dsk** [comment]
GOD FUCKING DAMN IT IT GOT FLOODED AGAIN

**Comment by vixfwis** [comment]
looks like someone is deliberately trying to flood mirrors. got about 4k of those 

`66.249.93.220 - - [11/Jul/2021:06:57:09 +0000] "GET /Sneeds-Feed-and-Seed/sneedacity/raw/branch/master/tests/samples/FifeAndDrumsStereo.wav?r=52 HTTP/1.1" 502 157 "-" "Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)"
66.249.93.220 - - [11/Jul/2021:06:57:09 +0000] "GET /Sneeds-Feed-and-Seed/sneedacity/raw/branch/master/tests/samples/FifeAndDrumsStereo.wav?r=60 HTTP/1.1" 502 157 "-" "Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)"
66.249.93.220 - - [11/Jul/2021:06:57:09 +0000] "GET /Sneeds-Feed-and-Seed/sneedacity/raw/branch/master/tests/samples/FifeAndDrumsStereo.wav?r=55 HTTP/1.1" 502 157 "-" "Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)"
66.249.93.220 - - [11/Jul/2021:06:57:09 +0000] "GET /Sneeds-Feed-and-Seed/sneedacity/raw/branch/master/tests/samples/FifeAndDrumsStereo.wav?r=62 HTTP/1.1" 502 157 "-" "Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)"
66.249.93.221 - - [11/Jul/2021:06:57:09 +0000] "GET /Sneeds-Feed-and-Seed/sneedacity/raw/branch/master/tests/samples/FifeAndDrumsStereo.wav?r=43 HTTP/1.1" 502 157 "-" "Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)"
66.249.93.220 - - [11/Jul/2021:06:57:09 +0000] "GET /Sneeds-Feed-and-Seed/sneedacity/raw/branch/master/tests/samples/FifeAndDrumsStereo.wav?r=45 HTTP/1.1" 502 157 "-" "Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)"
`

well shit I guess it's time to setup fail2ban

**Comment by eylles** [comment]
@vixfwis add a tar pit too.
https://github.com/skeeto/endlessh

**Comment by kakolisgay** [comment]
@vixfwis All of those are Google ip's, it's likely just a retarded media proxy on their end. Either rangeban the asn or configure your robots.txt to prevent google from using it's media proxy
