### ISSUE TITLE
Program crashes while exporting with 8000 project rate

### ISSUE THREAD

**Issue by twl-surrogate** [Sneeds-Feed-and-Seed/sneedacity#96]
**Describe the bug**
recorded thing with 8000 project rate and the program crashed when i try to render

**To Reproduce**
1. open sneedacity
2. change project rate to 8000
3. record something
4. try to render

**Expected behavior**
uh it is supposed to render it

**Screenshots**
n/a

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]
 - Debian Unstable/Sid
 - Version [e.g. Sneedacity 2.5.1]
 - idk
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]
 - audio thing is alsa but the recording works and plays back in the program alright

**Additional context**
sneed

**Comment by twl-surrogate** [comment]
oh this happens on every rate maybe i fucked up the install or something

**Comment by Furitenman** [comment]
It seems to be working for me. Have you checked that you're not missing any library?

**Comment by mariaWitch** [comment]
Please check to see if this issue still appears with the newest version.

**Comment by twl-surrogate** [comment]
> Please check to see if this issue still appears with the newest version.

i tried the latest appimage on my laptop and it seems to work fine, will try it on the computer that had the issue later

**Comment by mariaWitch** [comment]
Any update? It seems that it is resolved, so unless you are still having issues I'll close this within 48 hours.

**Comment by twl-surrogate** [comment]
i downloaded the newest appimage and it seems to work now, it did complain about ffmpeg missing or whatever, but it work so i can just deal with that later
